/**
 * Component Migration Registry
 * 
 * Tracks the migration status of every UI component from the current
 * "Bold Contemporary Pop Art" design system to the ClickUp 4.0 specification.
 * 
 * Status Legend:
 * - 'legacy': Original component, not yet migrated
 * - 'in-progress': Migration started, not complete
 * - 'migrated': New component built, old still exists
 * - 'verified': Feature parity verified, ready for deprecation
 * - 'complete': Migration complete, old component removed
 */

export type MigrationStatus = 
  | 'legacy' 
  | 'in-progress' 
  | 'migrated' 
  | 'verified' 
  | 'complete';

export type AtomicLevel = 
  | 'atom' 
  | 'molecule' 
  | 'organism' 
  | 'template' 
  | 'page';

export type Priority = 'P0' | 'P1' | 'P2' | 'P3';

export interface ComponentMigration {
  /** Component name */
  name: string;
  /** Current file path */
  currentPath: string;
  /** Target path after migration */
  targetPath: string;
  /** Atomic design level */
  atomicLevel: AtomicLevel;
  /** Migration status */
  status: MigrationStatus;
  /** Migration priority */
  priority: Priority;
  /** Has TypeScript types file */
  hasTypes: boolean;
  /** Has CVA variants file */
  hasVariants: boolean;
  /** Has Storybook stories */
  hasStories: boolean;
  /** Has unit tests */
  hasTests: boolean;
  /** Uses design tokens exclusively */
  usesTokens: boolean;
  /** Supports dark mode */
  supportsDarkMode: boolean;
  /** WCAG AA compliant */
  isAccessible: boolean;
  /** Whitelabel compatible */
  isWhitelabelReady: boolean;
  /** Components that depend on this one */
  dependents: string[];
  /** Components this one depends on */
  dependencies: string[];
  /** Known issues or blockers */
  issues: string[];
  /** Migration notes */
  notes: string;
}

// =============================================================================
// ATOMS REGISTRY
// =============================================================================

export const atomsRegistry: ComponentMigration[] = [
  {
    name: 'Button',
    currentPath: 'packages/ui/src/atoms/button.tsx',
    targetPath: 'packages/ui/src/atoms/Button/Button.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ButtonGroup', 'Modal', 'Form', 'Card', 'Alert'],
    dependencies: ['Icon', 'Spinner'],
    issues: ['Uses hardcoded Tailwind classes', 'No CVA variants'],
    notes: 'Core atom - migrate first',
  },
  {
    name: 'Input',
    currentPath: 'packages/ui/src/atoms/input.tsx',
    targetPath: 'packages/ui/src/atoms/Input/Input.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Field', 'SearchFilter', 'AuthFormField'],
    dependencies: ['Icon'],
    issues: ['Uses hardcoded Tailwind classes'],
    notes: 'Core atom - migrate with Button',
  },
  {
    name: 'Typography',
    currentPath: 'packages/ui/src/atoms/typography.tsx',
    targetPath: 'packages/ui/src/atoms/Typography/Typography.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Card', 'Modal', 'Alert', 'StatCard'],
    dependencies: [],
    issues: ['Uses pop-art fonts (Anton/Bebas)', 'Hardcoded letter-spacing'],
    notes: 'Exports Display, H1-H6, Body, Label',
  },
  {
    name: 'Avatar',
    currentPath: 'packages/ui/src/atoms/avatar.tsx',
    targetPath: 'packages/ui/src/atoms/Avatar/Avatar.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AvatarGroup', 'PresenceAvatars', 'CrewCard'],
    dependencies: [],
    issues: ['Has inline styles'],
    notes: 'Also exports AvatarGroup',
  },
  {
    name: 'Badge',
    currentPath: 'packages/ui/src/atoms/badge.tsx',
    targetPath: 'packages/ui/src/atoms/Badge/Badge.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['StatusBadge', 'UrgencyBadge', 'Card'],
    dependencies: [],
    issues: ['1 hardcoded color'],
    notes: 'Base badge component',
  },
  {
    name: 'Checkbox',
    currentPath: 'packages/ui/src/atoms/checkbox.tsx',
    targetPath: 'packages/ui/src/atoms/Checkbox/Checkbox.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Form', 'DataGrid', 'BulkActionBar'],
    dependencies: [],
    issues: [],
    notes: 'Proper atomic structure',
  },
  {
    name: 'Radio',
    currentPath: 'packages/ui/src/atoms/radio.tsx',
    targetPath: 'packages/ui/src/atoms/Radio/Radio.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Form', 'RecordFormModal'],
    dependencies: [],
    issues: [],
    notes: 'Proper atomic structure',
  },
  {
    name: 'Select',
    currentPath: 'packages/ui/src/atoms/select.tsx',
    targetPath: 'packages/ui/src/atoms/Select/Select.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Field', 'SearchFilter', 'RecordFormModal'],
    dependencies: ['Icon'],
    issues: ['Has inline style'],
    notes: 'Core form atom',
  },
  {
    name: 'Switch',
    currentPath: 'packages/ui/src/atoms/switch.tsx',
    targetPath: 'packages/ui/src/atoms/Switch/Switch.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['SettingsRow', 'Form'],
    dependencies: [],
    issues: [],
    notes: 'Toggle switch component',
  },
  {
    name: 'Textarea',
    currentPath: 'packages/ui/src/atoms/textarea.tsx',
    targetPath: 'packages/ui/src/atoms/Textarea/Textarea.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Field', 'RecordFormModal'],
    dependencies: [],
    issues: [],
    notes: 'Multi-line text input',
  },
  {
    name: 'Spinner',
    currentPath: 'packages/ui/src/atoms/spinner.tsx',
    targetPath: 'packages/ui/src/atoms/Spinner/Spinner.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Button', 'Skeleton', 'LoadingState'],
    dependencies: [],
    issues: [],
    notes: 'Loading indicator',
  },
  {
    name: 'ProgressBar',
    currentPath: 'packages/ui/src/atoms/progress-bar.tsx',
    targetPath: 'packages/ui/src/atoms/ProgressBar/ProgressBar.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['FileUpload', 'Stepper'],
    dependencies: [],
    issues: ['Has inline style'],
    notes: 'Progress indicator',
  },
  {
    name: 'Tooltip',
    currentPath: 'packages/ui/src/atoms/tooltip.tsx',
    targetPath: 'packages/ui/src/atoms/Tooltip/Tooltip.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Button', 'Icon', 'DataGrid'],
    dependencies: [],
    issues: ['Has inline style'],
    notes: 'Hover tooltip',
  },
  {
    name: 'Divider',
    currentPath: 'packages/ui/src/atoms/divider.tsx',
    targetPath: 'packages/ui/src/atoms/Divider/Divider.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Card', 'Modal', 'Dropdown'],
    dependencies: [],
    issues: [],
    notes: 'Minimal, proper atomic',
  },
  {
    name: 'Icon',
    currentPath: 'packages/ui/src/atoms/icon.tsx',
    targetPath: 'packages/ui/src/atoms/Icon/Icon.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Button', 'Input', 'Select', 'Navigation'],
    dependencies: [],
    issues: ['Wraps Lucide icons'],
    notes: 'Icon wrapper component',
  },
  {
    name: 'Link',
    currentPath: 'packages/ui/src/atoms/link.tsx',
    targetPath: 'packages/ui/src/atoms/Link/Link.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Navigation', 'Breadcrumb', 'Footer'],
    dependencies: [],
    issues: [],
    notes: 'Navigation link',
  },
  {
    name: 'Text',
    currentPath: 'packages/ui/src/atoms/text.tsx',
    targetPath: 'packages/ui/src/atoms/Text/Text.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Card', 'Alert', 'EmptyState'],
    dependencies: [],
    issues: [],
    notes: 'Generic text component',
  },
  {
    name: 'PasswordInput',
    currentPath: 'packages/ui/src/atoms/password-input.tsx',
    targetPath: 'packages/ui/src/atoms/PasswordInput/PasswordInput.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AuthFormField', 'SignInForm'],
    dependencies: ['Input', 'Icon'],
    issues: ['6 hardcoded colors'],
    notes: 'Password with visibility toggle',
  },
  {
    name: 'PhoneInput',
    currentPath: 'packages/ui/src/atoms/phone-input.tsx',
    targetPath: 'packages/ui/src/atoms/PhoneInput/PhoneInput.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['RecordFormModal', 'CreatePage'],
    dependencies: ['Input', 'Select'],
    issues: ['Complex internationalization'],
    notes: 'International phone input',
  },
  {
    name: 'AddressInput',
    currentPath: 'packages/ui/src/atoms/address-input.tsx',
    targetPath: 'packages/ui/src/atoms/AddressInput/AddressInput.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['RecordFormModal', 'CreatePage'],
    dependencies: ['Input'],
    issues: ['4 hardcoded colors'],
    notes: 'Address autocomplete',
  },
  {
    name: 'Sparkline',
    currentPath: 'packages/ui/src/atoms/sparkline.tsx',
    targetPath: 'packages/ui/src/atoms/Sparkline/Sparkline.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['StatCard', 'StatsDashboard'],
    dependencies: [],
    issues: ['6 hardcoded colors', 'Has inline styles'],
    notes: 'Mini chart component',
  },
  {
    name: 'StatusBadge',
    currentPath: 'packages/ui/src/atoms/status-badge.tsx',
    targetPath: 'packages/ui/src/atoms/StatusBadge/StatusBadge.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['DataGrid', 'KanbanBoard', 'Card'],
    dependencies: ['Badge'],
    issues: [],
    notes: 'Status-specific badge',
  },
  {
    name: 'UrgencyBadge',
    currentPath: 'packages/ui/src/atoms/urgency-badge.tsx',
    targetPath: 'packages/ui/src/atoms/UrgencyBadge/UrgencyBadge.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['TicketCard', 'EventCard'],
    dependencies: ['Badge'],
    issues: ['2 hardcoded colors'],
    notes: 'Priority/urgency indicator',
  },
  {
    name: 'Countdown',
    currentPath: 'packages/ui/src/atoms/countdown.tsx',
    targetPath: 'packages/ui/src/atoms/Countdown/Countdown.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['EventCard', 'TicketCard'],
    dependencies: [],
    issues: ['2 hardcoded colors'],
    notes: 'Countdown timer',
  },
  {
    name: 'SocialIcon',
    currentPath: 'packages/ui/src/atoms/social-icon.tsx',
    targetPath: 'packages/ui/src/atoms/SocialIcon/SocialIcon.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P3',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['Footer', 'AuthFormField'],
    dependencies: [],
    issues: ['2 hardcoded colors'],
    notes: 'Social media icons',
  },
  {
    name: 'GeometricShapes',
    currentPath: 'packages/ui/src/atoms/geometric-shapes.tsx',
    targetPath: 'packages/ui/src/atoms/GeometricShapes/GeometricShapes.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P3',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['Hero', 'MarketingPage'],
    dependencies: [],
    issues: ['11 inline styles', 'Pop-art specific'],
    notes: 'Decorative shapes - may deprecate',
  },
  {
    name: 'HalftonePattern',
    currentPath: 'packages/ui/src/atoms/halftone-pattern.tsx',
    targetPath: 'packages/ui/src/atoms/HalftonePattern/HalftonePattern.tsx',
    atomicLevel: 'atom',
    status: 'legacy',
    priority: 'P3',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['Hero', 'MarketingPage'],
    dependencies: [],
    issues: ['Has inline styles', 'Pop-art specific'],
    notes: 'Decorative pattern - may deprecate',
  },
];

// =============================================================================
// MOLECULES REGISTRY
// =============================================================================

export const moleculesRegistry: ComponentMigration[] = [
  {
    name: 'Card',
    currentPath: 'packages/ui/src/molecules/card.tsx',
    targetPath: 'packages/ui/src/molecules/Card/Card.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['StatCard', 'EventCard', 'CrewCard', 'ProjectCard'],
    dependencies: ['Typography', 'Divider'],
    issues: ['Uses hardcoded Tailwind classes'],
    notes: 'Core molecule - exports CardHeader, CardBody, CardFooter',
  },
  {
    name: 'Field',
    currentPath: 'packages/ui/src/molecules/field.tsx',
    targetPath: 'packages/ui/src/molecules/Field/Field.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['RecordFormModal', 'CreatePage', 'EditPage'],
    dependencies: ['Input', 'Select', 'Textarea', 'Label'],
    issues: [],
    notes: 'Form field wrapper with label/error',
  },
  {
    name: 'Alert',
    currentPath: 'packages/ui/src/molecules/alert.tsx',
    targetPath: 'packages/ui/src/molecules/Alert/Alert.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ErrorState', 'Form'],
    dependencies: ['Icon', 'Typography'],
    issues: [],
    notes: 'Alert/notification component',
  },
  {
    name: 'Table',
    currentPath: 'packages/ui/src/molecules/table.tsx',
    targetPath: 'packages/ui/src/molecules/Table/Table.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['DataGrid', 'ListPage'],
    dependencies: [],
    issues: [],
    notes: 'Base table components',
  },
  {
    name: 'Tabs',
    currentPath: 'packages/ui/src/molecules/tabs.tsx',
    targetPath: 'packages/ui/src/molecules/Tabs/Tabs.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['DetailPage', 'SettingsHubPage'],
    dependencies: [],
    issues: [],
    notes: 'Tab navigation component',
  },
  {
    name: 'Dropdown',
    currentPath: 'packages/ui/src/molecules/dropdown.tsx',
    targetPath: 'packages/ui/src/molecules/Dropdown/Dropdown.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AppNavbar', 'RowActions'],
    dependencies: ['Button', 'Icon'],
    issues: [],
    notes: 'Dropdown menu',
  },
  {
    name: 'Pagination',
    currentPath: 'packages/ui/src/molecules/pagination.tsx',
    targetPath: 'packages/ui/src/molecules/Pagination/Pagination.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['DataGrid', 'ListPage'],
    dependencies: ['Button', 'Icon'],
    issues: [],
    notes: 'Pagination controls',
  },
  {
    name: 'Breadcrumb',
    currentPath: 'packages/ui/src/molecules/breadcrumb.tsx',
    targetPath: 'packages/ui/src/molecules/Breadcrumb/Breadcrumb.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AppPageHeader', 'DetailPage'],
    dependencies: ['Link', 'Icon'],
    issues: [],
    notes: 'Navigation breadcrumbs',
  },
  {
    name: 'SearchFilter',
    currentPath: 'packages/ui/src/molecules/search-filter.tsx',
    targetPath: 'packages/ui/src/molecules/SearchFilter/SearchFilter.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage', 'DataGrid'],
    dependencies: ['Input', 'Select', 'Button'],
    issues: [],
    notes: 'Search and filter controls',
  },
  {
    name: 'EmptyState',
    currentPath: 'packages/ui/src/molecules/empty-state.tsx',
    targetPath: 'packages/ui/src/molecules/EmptyState/EmptyState.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage', 'DataGrid', 'KanbanBoard'],
    dependencies: ['Icon', 'Typography', 'Button'],
    issues: [],
    notes: 'Empty state placeholder',
  },
  {
    name: 'ErrorState',
    currentPath: 'packages/ui/src/molecules/error-state.tsx',
    targetPath: 'packages/ui/src/molecules/ErrorState/ErrorState.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage', 'DetailPage', 'ErrorBoundary'],
    dependencies: ['Icon', 'Typography', 'Button'],
    issues: [],
    notes: 'Error state display',
  },
  {
    name: 'Skeleton',
    currentPath: 'packages/ui/src/molecules/skeleton.tsx',
    targetPath: 'packages/ui/src/molecules/Skeleton/Skeleton.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage', 'DetailPage', 'Card'],
    dependencies: [],
    issues: ['2 hardcoded colors', 'Has inline style'],
    notes: 'Loading skeleton',
  },
  {
    name: 'FloorPlanObjectLibrary',
    currentPath: 'packages/ui/src/molecules/floor-plan-object-library.tsx',
    targetPath: 'packages/ui/src/molecules/FloorPlanObjectLibrary/FloorPlanObjectLibrary.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P3',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['FloorPlanCanvas'],
    dependencies: [],
    issues: ['26 hardcoded colors', 'Has inline style'],
    notes: 'Floor plan editor objects - needs major refactor',
  },
  {
    name: 'AuthFormField',
    currentPath: 'packages/ui/src/molecules/auth-form-field.tsx',
    targetPath: 'packages/ui/src/molecules/AuthFormField/AuthFormField.tsx',
    atomicLevel: 'molecule',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['SignInForm', 'AuthSplitLayout'],
    dependencies: ['Input', 'PasswordInput', 'Checkbox'],
    issues: ['10 hardcoded colors'],
    notes: 'Auth-specific form fields',
  },
];

// =============================================================================
// ORGANISMS REGISTRY
// =============================================================================

export const organismsRegistry: ComponentMigration[] = [
  {
    name: 'Modal',
    currentPath: 'packages/ui/src/organisms/modal.tsx',
    targetPath: 'packages/ui/src/organisms/Modal/Modal.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['RecordFormModal', 'ConfirmDialog', 'BulkEditModal'],
    dependencies: ['Button', 'Icon', 'Typography'],
    issues: ['4 hardcoded colors'],
    notes: 'Core modal - exports ModalHeader, ModalBody, ModalFooter',
  },
  {
    name: 'AppSidebar',
    currentPath: 'packages/ui/src/organisms/app-sidebar.tsx',
    targetPath: 'packages/ui/src/organisms/AppSidebar/AppSidebar.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AuthenticatedShell'],
    dependencies: ['Icon', 'Link', 'Avatar', 'Tooltip'],
    issues: ['1 hardcoded color', '2 inline styles'],
    notes: 'Main navigation sidebar - needs ClickUp 4.0 alignment',
  },
  {
    name: 'AppNavbar',
    currentPath: 'packages/ui/src/organisms/app-navbar.tsx',
    targetPath: 'packages/ui/src/organisms/AppNavbar/AppNavbar.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AuthenticatedShell'],
    dependencies: ['Button', 'Icon', 'Avatar', 'Dropdown', 'Breadcrumb'],
    issues: [],
    notes: 'Top navigation bar',
  },
  {
    name: 'DataGrid',
    currentPath: 'packages/ui/src/organisms/data-grid.tsx',
    targetPath: 'packages/ui/src/organisms/DataGrid/DataGrid.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage'],
    dependencies: ['Table', 'Checkbox', 'Pagination', 'Skeleton'],
    issues: [],
    notes: 'Data table - needs ClickUp 4.0 features',
  },
  {
    name: 'KanbanBoard',
    currentPath: 'packages/ui/src/organisms/kanban-board.tsx',
    targetPath: 'packages/ui/src/organisms/KanbanBoard/KanbanBoard.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage'],
    dependencies: ['Card', 'StatusBadge', 'Avatar'],
    issues: ['1 hardcoded color', '2 inline styles'],
    notes: 'Kanban board view',
  },
  {
    name: 'Calendar',
    currentPath: 'packages/ui/src/organisms/calendar.tsx',
    targetPath: 'packages/ui/src/organisms/Calendar/Calendar.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage', 'MasterCalendar'],
    dependencies: ['Button', 'Icon'],
    issues: ['6 hardcoded colors', '3 inline styles'],
    notes: 'Calendar view',
  },
  {
    name: 'GanttChart',
    currentPath: 'packages/ui/src/organisms/gantt-chart.tsx',
    targetPath: 'packages/ui/src/organisms/GanttChart/GanttChart.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['ListPage'],
    dependencies: [],
    issues: ['8 hardcoded colors', '11 inline styles'],
    notes: 'Gantt chart view - needs major refactor',
  },
  {
    name: 'TimelineView',
    currentPath: 'packages/ui/src/organisms/timeline-view.tsx',
    targetPath: 'packages/ui/src/organisms/TimelineView/TimelineView.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['ListPage'],
    dependencies: ['Card', 'Avatar'],
    issues: ['6 hardcoded colors'],
    notes: 'Timeline view',
  },
  {
    name: 'MapView',
    currentPath: 'packages/ui/src/organisms/map-view.tsx',
    targetPath: 'packages/ui/src/organisms/MapView/MapView.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['ListPage'],
    dependencies: [],
    issues: ['9 hardcoded colors', '8 inline styles'],
    notes: 'Map view - needs major refactor',
  },
  {
    name: 'StatsDashboard',
    currentPath: 'packages/ui/src/organisms/stats-dashboard.tsx',
    targetPath: 'packages/ui/src/organisms/StatsDashboard/StatsDashboard.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P2',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['DashboardPage'],
    dependencies: ['Card', 'Sparkline'],
    issues: ['8 hardcoded colors'],
    notes: 'Dashboard statistics',
  },
  {
    name: 'CommandPalette',
    currentPath: 'packages/ui/src/organisms/command-palette.tsx',
    targetPath: 'packages/ui/src/organisms/CommandPalette/CommandPalette.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: ['AuthenticatedShell'],
    dependencies: ['Input', 'Icon'],
    issues: [],
    notes: 'Command palette - needs ClickUp 4.0 alignment',
  },
  {
    name: 'SeatingChart',
    currentPath: 'packages/ui/src/organisms/seating-chart.tsx',
    targetPath: 'packages/ui/src/organisms/SeatingChart/SeatingChart.tsx',
    atomicLevel: 'organism',
    status: 'legacy',
    priority: 'P3',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: false,
    isWhitelabelReady: false,
    dependents: ['EventDetailPage'],
    dependencies: [],
    issues: ['10 inline styles'],
    notes: 'Seating chart - specialized component',
  },
];

// =============================================================================
// TEMPLATES REGISTRY
// =============================================================================

export const templatesRegistry: ComponentMigration[] = [
  {
    name: 'ListPage',
    currentPath: 'packages/ui/src/templates/list-page.tsx',
    targetPath: 'packages/ui/src/templates/ListPage/ListPage.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['DataGrid', 'KanbanBoard', 'SearchFilter', 'Pagination'],
    issues: ['68.5KB - very large file'],
    notes: 'Primary list/table template - needs refactor',
  },
  {
    name: 'DetailPage',
    currentPath: 'packages/ui/src/templates/detail-page.tsx',
    targetPath: 'packages/ui/src/templates/DetailPage/DetailPage.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['Tabs', 'Breadcrumb', 'Button'],
    issues: [],
    notes: 'Entity detail view template',
  },
  {
    name: 'AuthenticatedShell',
    currentPath: 'packages/ui/src/templates/authenticated-shell.tsx',
    targetPath: 'packages/ui/src/templates/AuthenticatedShell/AuthenticatedShell.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P0',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['AppSidebar', 'AppNavbar', 'CommandPalette'],
    issues: [],
    notes: 'Main app shell template',
  },
  {
    name: 'CreatePage',
    currentPath: 'packages/ui/src/templates/create-page.tsx',
    targetPath: 'packages/ui/src/templates/CreatePage/CreatePage.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['Field', 'Button', 'Card'],
    issues: [],
    notes: 'Create form template',
  },
  {
    name: 'EditPage',
    currentPath: 'packages/ui/src/templates/edit-page.tsx',
    targetPath: 'packages/ui/src/templates/EditPage/EditPage.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['Field', 'Button', 'Card'],
    issues: [],
    notes: 'Edit form template',
  },
  {
    name: 'DashboardPage',
    currentPath: 'packages/ui/src/templates/dashboard-page.tsx',
    targetPath: 'packages/ui/src/templates/DashboardPage/DashboardPage.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['StatsDashboard', 'Card'],
    issues: [],
    notes: 'Dashboard template',
  },
  {
    name: 'AuthSplitLayout',
    currentPath: 'packages/ui/src/templates/auth-split-layout.tsx',
    targetPath: 'packages/ui/src/templates/AuthSplitLayout/AuthSplitLayout.tsx',
    atomicLevel: 'template',
    status: 'legacy',
    priority: 'P1',
    hasTypes: false,
    hasVariants: false,
    hasStories: false,
    hasTests: false,
    usesTokens: false,
    supportsDarkMode: false,
    isAccessible: true,
    isWhitelabelReady: false,
    dependents: [],
    dependencies: ['AuthFormField'],
    issues: [],
    notes: 'Auth page template',
  },
];

// =============================================================================
// REGISTRY AGGREGATION
// =============================================================================

export const componentRegistry = {
  atoms: atomsRegistry,
  molecules: moleculesRegistry,
  organisms: organismsRegistry,
  templates: templatesRegistry,
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export const getComponentsByStatus = (status: MigrationStatus): ComponentMigration[] => {
  return [
    ...atomsRegistry,
    ...moleculesRegistry,
    ...organismsRegistry,
    ...templatesRegistry,
  ].filter(c => c.status === status);
};

export const getComponentsByPriority = (priority: Priority): ComponentMigration[] => {
  return [
    ...atomsRegistry,
    ...moleculesRegistry,
    ...organismsRegistry,
    ...templatesRegistry,
  ].filter(c => c.priority === priority);
};

export const getComponentsWithIssues = (): ComponentMigration[] => {
  return [
    ...atomsRegistry,
    ...moleculesRegistry,
    ...organismsRegistry,
    ...templatesRegistry,
  ].filter(c => c.issues.length > 0);
};

export const getMigrationStats = () => {
  const all = [
    ...atomsRegistry,
    ...moleculesRegistry,
    ...organismsRegistry,
    ...templatesRegistry,
  ];
  
  return {
    total: all.length,
    byStatus: {
      legacy: all.filter(c => c.status === 'legacy').length,
      inProgress: all.filter(c => c.status === 'in-progress').length,
      migrated: all.filter(c => c.status === 'migrated').length,
      verified: all.filter(c => c.status === 'verified').length,
      complete: all.filter(c => c.status === 'complete').length,
    },
    byPriority: {
      P0: all.filter(c => c.priority === 'P0').length,
      P1: all.filter(c => c.priority === 'P1').length,
      P2: all.filter(c => c.priority === 'P2').length,
      P3: all.filter(c => c.priority === 'P3').length,
    },
    byLevel: {
      atoms: atomsRegistry.length,
      molecules: moleculesRegistry.length,
      organisms: organismsRegistry.length,
      templates: templatesRegistry.length,
    },
    withIssues: all.filter(c => c.issues.length > 0).length,
    withTests: all.filter(c => c.hasTests).length,
    withStories: all.filter(c => c.hasStories).length,
    usingTokens: all.filter(c => c.usesTokens).length,
    darkModeReady: all.filter(c => c.supportsDarkMode).length,
    whitelabelReady: all.filter(c => c.isWhitelabelReady).length,
  };
};
