#!/usr/bin/env ts-node
/**
 * Entity Configuration Generator
 * 
 * Generates a new entity configuration file with SSOT-compliant structure.
 * Ensures all new entities follow the established patterns and integrate
 * with the Legend 3NF schema.
 * 
 * Usage:
 *   pnpm generate:entity <entity-name> [options]
 * 
 * Examples:
 *   pnpm generate:entity venues
 *   pnpm generate:entity sponsors --legend-table=legend_organizations
 *   pnpm generate:entity schedules --legend-table=legend_events --app=atlvs
 */

import * as fs from 'fs';
import * as path from 'path';

// ============================================================================
// Types
// ============================================================================

interface EntityGeneratorOptions {
  name: string;
  singular?: string;
  plural?: string;
  legendTable?: string;
  app?: 'atlvs' | 'compvss' | 'gvteway';
  icon?: string;
  description?: string;
}

// ============================================================================
// Legend Table Mappings
// ============================================================================

const LEGEND_TABLES = [
  'legend_people',
  'legend_places',
  'legend_organizations',
  'legend_products',
  'legend_events',
  'legend_documents',
] as const;

type LegendTable = typeof LEGEND_TABLES[number];

const LEGEND_TABLE_DEFAULTS: Record<LegendTable, { icon: string; statuses: string[] }> = {
  legend_people: {
    icon: 'Users',
    statuses: ['active', 'inactive', 'pending', 'suspended'],
  },
  legend_places: {
    icon: 'MapPin',
    statuses: ['active', 'inactive', 'maintenance', 'closed'],
  },
  legend_organizations: {
    icon: 'Building2',
    statuses: ['active', 'inactive', 'pending', 'suspended'],
  },
  legend_products: {
    icon: 'Package',
    statuses: ['available', 'unavailable', 'maintenance', 'retired'],
  },
  legend_events: {
    icon: 'Calendar',
    statuses: ['draft', 'scheduled', 'active', 'completed', 'cancelled'],
  },
  legend_documents: {
    icon: 'FileText',
    statuses: ['draft', 'pending', 'approved', 'rejected', 'archived'],
  },
};

// ============================================================================
// Helpers
// ============================================================================

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map(capitalize)
    .join('');
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s-]+/g, '_')
    .toLowerCase();
}

function singularize(str: string): string {
  if (str.endsWith('ies')) return str.slice(0, -3) + 'y';
  if (str.endsWith('es')) return str.slice(0, -2);
  if (str.endsWith('s')) return str.slice(0, -1);
  return str;
}

function pluralize(str: string): string {
  if (str.endsWith('ies')) return str;
  if (str.endsWith('y')) return str.slice(0, -1) + 'ies';
  if (str.endsWith('s') || str.endsWith('x') || str.endsWith('ch') || str.endsWith('sh')) {
    return str + 'es';
  }
  return str + 's';
}

// Use pluralize in template generation
const ensurePlural = (name: string, plural?: string): string => plural || pluralize(name);

// ============================================================================
// Template Generator
// ============================================================================

function generateEntityTemplate(options: EntityGeneratorOptions): string {
  const {
    name,
    singular = singularize(name),
    plural = name,
    legendTable = 'legend_documents',
    icon = LEGEND_TABLE_DEFAULTS[legendTable as LegendTable]?.icon || 'FileText',
    description = `Manage ${plural}`,
  } = options;

  const pascalName = toPascalCase(singular);
  const snakeName = toSnakeCase(name);
  const kebabName = toKebabCase(name);
  const upperSnakeName = snakeName.toUpperCase();
  const defaults = LEGEND_TABLE_DEFAULTS[legendTable as LegendTable] || LEGEND_TABLE_DEFAULTS.legend_documents;

  return `/**
 * ${pascalName} Entity Configuration
 * 
 * SSOT-compliant entity configuration for ${plural}.
 * Integrates with Legend 3NF schema via ${legendTable}.
 * 
 * @generated by scripts/generate-entity.ts
 */

import type { EntityConfig } from '../types';
import type { StatusVariant } from '../types';
import {
  viewRowAction,
  editRowAction,
  deleteRowAction,
  deleteBulkAction,
} from '../common-actions';

// ============================================================================
// Status Colors (SSOT)
// ============================================================================

export const ${upperSnakeName}_STATUS_COLORS: Record<string, StatusVariant> = {
${defaults.statuses.map(s => `  ${s}: '${getStatusVariant(s)}',`).join('\n')}
};

// ============================================================================
// Entity Configuration
// ============================================================================

export const ${name}Entity: EntityConfig = {
  // ──────────────────────────────────────────────────────────────────────────
  // Identity
  // ──────────────────────────────────────────────────────────────────────────
  name: '${kebabName}',
  singular: '${capitalize(singular)}',
  plural: '${capitalize(plural)}',
  description: '${description}',
  icon: '${icon}',

  // ──────────────────────────────────────────────────────────────────────────
  // Legend 3NF Integration
  // ──────────────────────────────────────────────────────────────────────────
  legendTable: '${legendTable}',
  legendType: '${singular}',

  // ──────────────────────────────────────────────────────────────────────────
  // Routes
  // ──────────────────────────────────────────────────────────────────────────
  routes: {
    list: '/${kebabName}',
    detail: '/${kebabName}/[id]',
    create: '/${kebabName}/new',
    edit: '/${kebabName}/[id]/edit',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // API Configuration
  // ──────────────────────────────────────────────────────────────────────────
  api: {
    baseUrl: '/api/${kebabName}',
    endpoints: {
      list: '',
      detail: '/:id',
      create: '',
      update: '/:id',
      delete: '/:id',
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Columns (for ListPage)
  // ──────────────────────────────────────────────────────────────────────────
  columns: [
    {
      key: 'name',
      label: 'Name',
      accessor: 'name',
      sortable: true,
      searchable: true,
    },
    {
      key: 'status',
      label: 'Status',
      accessor: 'status',
      sortable: true,
      type: 'status',
    },
    {
      key: 'created_at',
      label: 'Created',
      accessor: 'created_at',
      sortable: true,
      type: 'date',
    },
    {
      key: 'updated_at',
      label: 'Updated',
      accessor: 'updated_at',
      sortable: true,
      type: 'date',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Filters
  // ──────────────────────────────────────────────────────────────────────────
  filters: [
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: [
${defaults.statuses.map(s => `        { value: '${s}', label: '${capitalize(s)}' },`).join('\n')}
      ],
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Row Actions
  // ──────────────────────────────────────────────────────────────────────────
  rowActions: [
    viewRowAction,
    editRowAction,
    deleteRowAction,
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Bulk Actions
  // ──────────────────────────────────────────────────────────────────────────
  bulkActions: [
    deleteBulkAction,
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Quick Actions
  // ──────────────────────────────────────────────────────────────────────────
  quickActions: [
    {
      id: 'create',
      label: 'New ${capitalize(singular)}',
      icon: 'Plus',
      variant: 'primary',
      route: '/${kebabName}/new',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Form Fields (for CreatePage/EditPage)
  // ──────────────────────────────────────────────────────────────────────────
  formFields: [
    {
      name: 'name',
      label: 'Name',
      type: 'text',
      required: true,
      placeholder: 'Enter ${singular} name',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Enter description',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      defaultValue: '${defaults.statuses[0]}',
      options: [
${defaults.statuses.map(s => `        { value: '${s}', label: '${capitalize(s)}' },`).join('\n')}
      ],
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Detail Sections (for DetailPage)
  // ──────────────────────────────────────────────────────────────────────────
  detailSections: [
    {
      id: 'overview',
      title: 'Overview',
      fields: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'description', label: 'Description', type: 'text' },
        { key: 'status', label: 'Status', type: 'status' },
      ],
    },
    {
      id: 'metadata',
      title: 'Metadata',
      fields: [
        { key: 'created_at', label: 'Created', type: 'datetime' },
        { key: 'updated_at', label: 'Updated', type: 'datetime' },
      ],
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Stats (for ListPage header)
  // ──────────────────────────────────────────────────────────────────────────
  stats: [
    {
      id: 'total',
      label: 'Total ${capitalize(plural)}',
      accessor: 'total',
      icon: '${icon}',
    },
    {
      id: 'active',
      label: 'Active',
      accessor: 'active',
      icon: 'CheckCircle',
    },
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // Features
  // ──────────────────────────────────────────────────────────────────────────
  features: {
    search: true,
    filter: true,
    sort: true,
    pagination: true,
    bulkActions: true,
    export: true,
    import: false,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Permissions
  // ──────────────────────────────────────────────────────────────────────────
  permissions: {
    view: ['viewer', 'editor', 'admin'],
    create: ['editor', 'admin'],
    edit: ['editor', 'admin'],
    delete: ['admin'],
    export: ['editor', 'admin'],
    import: ['admin'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Empty State
  // ──────────────────────────────────────────────────────────────────────────
  emptyState: {
    title: 'No ${plural} found',
    description: 'Get started by creating your first ${singular}.',
    action: {
      label: 'Create ${capitalize(singular)}',
      route: '/${kebabName}/new',
    },
  },
};

export default ${name}Entity;
`;
}

function getStatusVariant(status: string): string {
  const successStatuses = ['active', 'approved', 'completed', 'available', 'verified'];
  const warningStatuses = ['pending', 'draft', 'maintenance', 'scheduled'];
  const errorStatuses = ['inactive', 'rejected', 'cancelled', 'suspended', 'closed', 'retired', 'unavailable'];
  const infoStatuses = ['archived', 'processing'];

  if (successStatuses.includes(status)) return 'success';
  if (warningStatuses.includes(status)) return 'warning';
  if (errorStatuses.includes(status)) return 'error';
  if (infoStatuses.includes(status)) return 'info';
  return 'ghost';
}

// ============================================================================
// Main
// ============================================================================

function main() {
  const args = process.argv.slice(2);
  
  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log(`
Entity Configuration Generator

Usage:
  pnpm generate:entity <entity-name> [options]

Options:
  --singular=<name>       Singular form of entity name
  --plural=<name>         Plural form of entity name
  --legend-table=<table>  Legend 3NF table (default: legend_documents)
                          Options: ${LEGEND_TABLES.join(', ')}
  --app=<app>             Target app (atlvs, compvss, gvteway)
  --icon=<icon>           Lucide icon name
  --description=<desc>    Entity description
  --help, -h              Show this help message

Examples:
  pnpm generate:entity venues
  pnpm generate:entity sponsors --legend-table=legend_organizations
  pnpm generate:entity schedules --legend-table=legend_events --app=atlvs
`);
    process.exit(0);
  }

  const name = args[0];
  const options: EntityGeneratorOptions = { name };

  // Parse options
  for (const arg of args.slice(1)) {
    if (arg.startsWith('--singular=')) {
      options.singular = arg.split('=')[1];
    } else if (arg.startsWith('--plural=')) {
      options.plural = arg.split('=')[1];
    } else if (arg.startsWith('--legend-table=')) {
      options.legendTable = arg.split('=')[1];
    } else if (arg.startsWith('--app=')) {
      options.app = arg.split('=')[1] as 'atlvs' | 'compvss' | 'gvteway';
    } else if (arg.startsWith('--icon=')) {
      options.icon = arg.split('=')[1];
    } else if (arg.startsWith('--description=')) {
      options.description = arg.split('=')[1];
    }
  }

  // Generate template
  const template = generateEntityTemplate(options);
  
  // Output path
  const outputDir = path.join(__dirname, '../packages/config/entity-registry/entities');
  const outputFile = path.join(outputDir, `${toKebabCase(name)}.ts`);

  // Check if file exists
  if (fs.existsSync(outputFile)) {
    console.error(`❌ Error: Entity file already exists: ${outputFile}`);
    console.error('   Use a different name or delete the existing file first.');
    process.exit(1);
  }

  // Write file
  fs.writeFileSync(outputFile, template);
  console.log(`✅ Generated entity configuration: ${outputFile}`);
  
  // Remind to update index
  console.log(`
📝 Next steps:
1. Add to entities/index.ts:
   import { ${name}Entity } from './${toKebabCase(name)}';
   
2. Add to allEntities array:
   ${name}Entity,
   
3. Add to ENTITY_NAMES:
   ${toSnakeCase(name).toUpperCase()}: '${toKebabCase(name)}',
   
4. Export status colors from status-mappings.ts:
   export { ${toSnakeCase(name).toUpperCase()}_STATUS_COLORS } from './entities/${toKebabCase(name)}';
`);
}

main();
