/**
 * CUSTOMER EXPERIENCE & SATISFACTION KPIs (176-200)
 * Experience Quality (176-190), Customer Service (191-200)
 */

import type { KPIDefinition } from './types/kpi-types';

export const CUSTOMER_EXPERIENCE_KPIS: KPIDefinition[] = [
  // Experience Quality (176-190)
  {
    id: 176,
    code: 'CX_EXP_001',
    name: 'Overall Satisfaction Score',
    description: 'Average rating of overall event experience',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['satisfaction_rating'] }],
    calculation: 'AVG(satisfaction_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'DISTRIBUTION'],
    targetValue: 8,
    warningThreshold: 7,
    criticalThreshold: 6,
    enabled: true
  },
  {
    id: 177,
    code: 'CX_EXP_002',
    name: 'Likelihood to Recommend',
    description: 'Percentage of attendees who would recommend event',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['would_recommend'] }],
    calculation: '(Would Recommend / Total Responses) × 100',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['GAUGE'],
    targetValue: 80,
    warningThreshold: 70,
    criticalThreshold: 60,
    enabled: true
  },
  {
    id: 178,
    code: 'CX_EXP_003',
    name: 'Experience vs Expectation Gap',
    description: 'Difference between expected and actual experience rating',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['expected_rating', 'actual_rating'] }],
    calculation: 'AVG(actual_rating - expected_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'BAR_CHART'],
    enabled: true
  },
  {
    id: 179,
    code: 'CX_EXP_004',
    name: 'Venue Experience Rating',
    description: 'Satisfaction with venue facilities and amenities',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['venue_rating'] }],
    calculation: 'AVG(venue_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 180,
    code: 'CX_EXP_005',
    name: 'Sound Quality Rating',
    description: 'Attendee rating of audio experience',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['sound_quality_rating'] }],
    calculation: 'AVG(sound_quality_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'DISTRIBUTION'],
    targetValue: 8,
    warningThreshold: 7,
    criticalThreshold: 6,
    enabled: true
  },
  {
    id: 181,
    code: 'CX_EXP_006',
    name: 'Visual Production Rating',
    description: 'Rating of lighting, screens, and visual effects',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['visual_production_rating'] }],
    calculation: 'AVG(visual_production_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 182,
    code: 'CX_EXP_007',
    name: 'F&B Service Quality',
    description: 'Satisfaction with food and beverage offerings',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['fb_service_rating'] }],
    calculation: 'AVG(fb_service_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 183,
    code: 'CX_EXP_008',
    name: 'Restroom Cleanliness Score',
    description: 'Rating of restroom facilities cleanliness',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['restroom_rating'] }],
    calculation: 'AVG(restroom_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 184,
    code: 'CX_EXP_009',
    name: 'Parking Experience Rating',
    description: 'Satisfaction with parking availability and convenience',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['parking_rating'] }],
    calculation: 'AVG(parking_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 185,
    code: 'CX_EXP_010',
    name: 'Accessibility Experience Score',
    description: 'Satisfaction of attendees with accessibility accommodations',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['accessibility_rating'] }],
    calculation: 'AVG(accessibility_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    targetValue: 9,
    warningThreshold: 8,
    criticalThreshold: 7,
    enabled: true
  },
  {
    id: 186,
    code: 'CX_EXP_011',
    name: 'Merchandise Quality Rating',
    description: 'Satisfaction with merchandise offerings and quality',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['merchandise_rating'] }],
    calculation: 'AVG(merchandise_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 187,
    code: 'CX_EXP_012',
    name: 'Staff Friendliness Score',
    description: 'Rating of staff courtesy and helpfulness',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['staff_friendliness_rating'] }],
    calculation: 'AVG(staff_friendliness_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    targetValue: 9,
    warningThreshold: 8,
    criticalThreshold: 7,
    enabled: true
  },
  {
    id: 188,
    code: 'CX_EXP_013',
    name: 'Event Flow Rating',
    description: 'Satisfaction with event pacing and schedule',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['event_flow_rating'] }],
    calculation: 'AVG(event_flow_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 189,
    code: 'CX_EXP_014',
    name: 'Queue Management Score',
    description: 'Satisfaction with wait times and line management',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['queue_management_rating'] }],
    calculation: 'AVG(queue_management_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 190,
    code: 'CX_EXP_015',
    name: 'Information Clarity Rating',
    description: 'Rating of how clear event information and signage was',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'EXPERIENCE_QUALITY',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['information_clarity_rating'] }],
    calculation: 'AVG(information_clarity_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  // Customer Service (191-200)
  {
    id: 191,
    code: 'CX_SVC_001',
    name: 'Support Ticket Resolution Time',
    description: 'Average hours to resolve customer support tickets',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'HOURS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['created_at', 'resolved_at'] }],
    calculation: 'AVG(resolved_at - created_at) in hours',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    targetValue: 12,
    warningThreshold: 24,
    criticalThreshold: 48,
    enabled: true
  },
  {
    id: 192,
    code: 'CX_SVC_002',
    name: 'First Contact Resolution Rate',
    description: 'Percentage of issues resolved on first contact',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['id', 'resolved_at'] }],
    calculation: '(First Contact Resolutions / Total Tickets) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    targetValue: 70,
    warningThreshold: 60,
    criticalThreshold: 50,
    enabled: true
  },
  {
    id: 193,
    code: 'CX_SVC_003',
    name: 'Customer Complaint Rate',
    description: 'Number of complaints per 100 attendees',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'RATE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'communications', fields: ['communication_type'] },
      { table: 'incidents', fields: ['id'] }
    ],
    calculation: '(COUNT(complaints) / Total Attendees) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER'],
    warningThreshold: 2,
    criticalThreshold: 5,
    enabled: true
  },
  {
    id: 194,
    code: 'CX_SVC_004',
    name: 'Refund Request Rate',
    description: 'Percentage of tickets with refund requests',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'tickets', fields: ['ticket_status', 'refund_amount'] }],
    calculation: '(Refund Requests / Total Tickets Sold) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    warningThreshold: 3,
    criticalThreshold: 5,
    enabled: true
  },
  {
    id: 195,
    code: 'CX_SVC_005',
    name: 'Support Satisfaction Score',
    description: 'Average rating of customer service interactions',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['support_rating'] }],
    calculation: 'AVG(support_rating)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER'],
    targetValue: 8,
    warningThreshold: 7,
    criticalThreshold: 6,
    enabled: true
  },
  {
    id: 196,
    code: 'CX_SVC_006',
    name: 'Live Chat Response Time',
    description: 'Average seconds to first response in live chat',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'SECONDS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['created_at', 'first_response_at'] }],
    calculation: 'AVG(first_response_time - message_received_time)',
    updateFrequency: 'REAL_TIME',
    visualizations: ['NUMBER'],
    targetValue: 60,
    warningThreshold: 120,
    criticalThreshold: 300,
    enabled: true
  },
  {
    id: 197,
    code: 'CX_SVC_007',
    name: 'Self-Service Success Rate',
    description: 'Percentage of customers who resolved issues via self-service',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'analytics_events', fields: ['event_name', 'page_url'] }],
    calculation: '(Self-Resolved / Total Inquiries) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 198,
    code: 'CX_SVC_008',
    name: 'Escalation Rate',
    description: 'Percentage of support tickets that required escalation',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['priority', 'metadata'] }],
    calculation: '(Escalated Tickets / Total Tickets) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    warningThreshold: 15,
    criticalThreshold: 25,
    enabled: true
  },
  {
    id: 199,
    code: 'CX_SVC_009',
    name: 'Follow-Up Completion Rate',
    description: 'Percentage of required follow-ups that were completed',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['follow_up_required', 'follow_up_completed'] }],
    calculation: '(Completed Follow-ups / Required Follow-ups) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    targetValue: 100,
    warningThreshold: 90,
    criticalThreshold: 80,
    enabled: true
  },
  {
    id: 200,
    code: 'CX_SVC_010',
    name: 'Service Recovery Success Rate',
    description: 'Percentage of complainants satisfied after complaint resolution',
    category: 'CUSTOMER_EXPERIENCE',
    subcategory: 'CUSTOMER_SERVICE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['post_resolution_satisfaction'] }],
    calculation: '(Satisfied after Resolution / Total Complaints) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    targetValue: 80,
    warningThreshold: 70,
    criticalThreshold: 60,
    enabled: true
  }
];
