/**
 * OPERATIONAL EFFICIENCY KPIs (91-145)
 * Project Management (91-110), Team Performance (111-130), Vendor & Supply Chain (131-145)
 */

import type { KPIDefinition } from './types/kpi-types';

export const OPERATIONAL_KPIS: KPIDefinition[] = [
  // Project Management (91-110)
  {
    id: 91,
    code: 'OPS_PM_001',
    name: 'Schedule Adherence Rate',
    description: 'Percentage of milestones completed on or before due date',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'project_milestones', fields: ['due_date', 'completed_at', 'is_completed'] }],
    calculation: '(On-time Milestones / Total Completed Milestones) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'LINE_CHART'],
    targetValue: 90,
    warningThreshold: 80,
    criticalThreshold: 70,
    enabled: true
  },
  {
    id: 92,
    code: 'OPS_PM_002',
    name: 'Project Timeline Adherence',
    description: 'Percentage of project staying on schedule',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'project_phases', fields: ['start_date', 'end_date'] },
      { table: 'project_milestones', fields: ['is_completed'] }
    ],
    calculation: '(Tasks On Schedule / Total Tasks) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 93,
    code: 'OPS_PM_003',
    name: 'Change Order Frequency',
    description: 'Number of change orders per total project scope items',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'RATIO',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['id', 'metadata'] }],
    calculation: 'COUNT(change orders) / Total Scope Items',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 94,
    code: 'OPS_PM_004',
    name: 'Risk Mitigation Success Rate',
    description: 'Percentage of identified risks that were successfully prevented/mitigated',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['metadata'] }],
    calculation: '(Prevented Risks / Total Identified Risks) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 95,
    code: 'OPS_PM_005',
    name: 'Milestone Completion Velocity',
    description: 'Average days ahead of (negative) or behind (positive) schedule',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'project_milestones', fields: ['due_date', 'completed_at'] }],
    calculation: 'AVG(completed_at - due_date)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 96,
    code: 'OPS_PM_006',
    name: 'Resource Allocation Efficiency',
    description: 'Percentage of allocated hours that were actually utilized',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'TARGET_RANGE',
    dataSources: [
      { table: 'staff_assignments', fields: ['scheduled_hours'] },
      { table: 'time_entries', fields: ['duration_minutes'] }
    ],
    calculation: '(Actual Hours Used / Allocated Hours) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    targetValue: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
    enabled: true
  },
  {
    id: 97,
    code: 'OPS_PM_007',
    name: 'Dependency Fulfillment Rate',
    description: 'Percentage of task dependencies met on time',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['depends_on_task_ids', 'task_status'] }],
    calculation: '(Dependencies Met on Time / Total Dependencies) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 98,
    code: 'OPS_PM_008',
    name: 'Critical Path Variance',
    description: 'Days ahead/behind on critical path timeline',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'project_milestones', fields: ['due_date', 'completed_at'], filters: ['is_critical = true'] },
      { table: 'tasks', fields: ['due_date', 'completed_at'], filters: ['is_critical = true'] }
    ],
    calculation: 'Actual Critical Path Duration - Planned Duration',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 99,
    code: 'OPS_PM_009',
    name: 'Average Task Duration',
    description: 'Average time to complete a task',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'DAYS',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'tasks', fields: ['created_at', 'completed_at'] }],
    calculation: 'AVG(completed_at - created_at)',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'DISTRIBUTION'],
    enabled: true
  },
  {
    id: 100,
    code: 'OPS_PM_010',
    name: 'Sprint Velocity',
    description: 'Average story points completed per sprint',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['story_points', 'metadata'] }],
    calculation: 'AVG(story points per sprint)',
    updateFrequency: 'WEEKLY',
    visualizations: ['LINE_CHART'],
    enabled: true
  },
  {
    id: 101,
    code: 'OPS_PM_011',
    name: 'Blocker Resolution Time',
    description: 'Average time to clear task blockers',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'HOURS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['task_status', 'updated_at'] }],
    calculation: 'AVG(time in blocked status)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 102,
    code: 'OPS_PM_012',
    name: 'Task Completion Rate',
    description: 'Percentage of all tasks marked as completed',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['task_status'] }],
    calculation: '(Completed Tasks / Total Tasks) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'PROGRESS_BAR'],
    enabled: true
  },
  {
    id: 103,
    code: 'OPS_PM_013',
    name: 'Overdue Task Percentage',
    description: 'Percentage of tasks past their due date',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['due_date', 'task_status'] }],
    calculation: '(Overdue Tasks / Total Active Tasks) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    warningThreshold: 10,
    criticalThreshold: 20,
    enabled: true
  },
  {
    id: 104,
    code: 'OPS_PM_014',
    name: 'Task Estimation Accuracy',
    description: 'Percentage difference between estimated and actual task duration',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'TARGET_RANGE',
    dataSources: [{ table: 'tasks', fields: ['estimated_hours', 'actual_hours'] }],
    calculation: 'AVG((actual_hours - estimated_hours) / estimated_hours) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'DISTRIBUTION'],
    targetValue: 0,
    warningThreshold: 20,
    criticalThreshold: 40,
    enabled: true
  },
  {
    id: 105,
    code: 'OPS_PM_015',
    name: 'Planning Accuracy',
    description: 'Percentage of project delivered within original scope/timeline/budget',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'events', fields: ['budget', 'event_start_date', 'event_end_date'] }],
    calculation: 'Composite score from scope/time/budget variances',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 106,
    code: 'OPS_PM_016',
    name: 'Scope Creep Index',
    description: 'Percentage increase in scope from original baseline',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['id', 'created_at'] }],
    calculation: '((Current Scope - Baseline Scope) / Baseline Scope) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'TREND_INDICATOR'],
    warningThreshold: 15,
    criticalThreshold: 30,
    enabled: true
  },
  {
    id: 107,
    code: 'OPS_PM_017',
    name: 'Communication Response Time',
    description: 'Average time to respond to project communications',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'HOURS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['created_at', 'read_at'] }],
    calculation: 'AVG(response_time - created_at)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 108,
    code: 'OPS_PM_018',
    name: 'Meeting Effectiveness Score',
    description: 'Percentage of meetings resulting in actionable outcomes',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'communications', fields: ['communication_type'], filters: ['communication_type = meeting'] },
      { table: 'tasks', fields: ['id'] }
    ],
    calculation: '(Meetings with Action Items / Total Meetings) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 109,
    code: 'OPS_PM_019',
    name: 'Decision Velocity',
    description: 'Average time from issue identification to decision',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'notes', fields: ['note_type', 'created_at'] }],
    calculation: 'AVG(decision_date - issue_identified_date)',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 110,
    code: 'OPS_PM_020',
    name: 'Project Health Score',
    description: 'Composite score of schedule, budget, scope, and quality',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'PROJECT_MANAGEMENT',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'kpi_data_points', fields: ['value', 'kpi_code'] }],
    calculation: 'Weighted average of component scores',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    targetValue: 75,
    warningThreshold: 60,
    criticalThreshold: 50,
    enabled: true
  },
  // Team Performance (111-130)
  {
    id: 111,
    code: 'OPS_TEAM_001',
    name: 'Staff Utilization Rate',
    description: 'Percentage of available staff hours that were billable/productive',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'TARGET_RANGE',
    dataSources: [
      { table: 'time_entries', fields: ['duration_minutes', 'is_billable'] },
      { table: 'staff_assignments', fields: ['scheduled_hours'] }
    ],
    calculation: '(Billable Hours / Total Available Hours) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'LINE_CHART'],
    targetValue: 82.5,
    warningThreshold: 75,
    criticalThreshold: 65,
    enabled: true
  },
  {
    id: 112,
    code: 'OPS_TEAM_002',
    name: 'Employee Satisfaction Score',
    description: 'Average satisfaction rating from post-event staff surveys',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['satisfaction_rating'], filters: ['survey_type = staff'] }],
    calculation: 'AVG(satisfaction_rating)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'TREND_INDICATOR'],
    targetValue: 8,
    warningThreshold: 7,
    criticalThreshold: 6,
    enabled: true
  },
  {
    id: 113,
    code: 'OPS_TEAM_003',
    name: 'Training Completion Rate',
    description: 'Percentage of required training completed by staff',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'users', fields: ['certifications'] }],
    calculation: '(Staff with Training Complete / Total Staff Requiring Training) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE', 'PROGRESS_BAR'],
    targetValue: 100,
    warningThreshold: 90,
    criticalThreshold: 80,
    enabled: true
  },
  {
    id: 114,
    code: 'OPS_TEAM_004',
    name: 'Cross-Training Index',
    description: 'Average number of roles each staff member is qualified for',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'users', fields: ['specialization'] },
      { table: 'staff_positions', fields: ['position_name'] }
    ],
    calculation: 'AVG(qualified positions per staff member)',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 115,
    code: 'OPS_TEAM_005',
    name: 'Staff Turnover Rate',
    description: 'Percentage of staff who left organization in period',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'user_organizations', fields: ['invitation_status', 'updated_at'] }],
    calculation: '(Departures / Average Staff Count) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    warningThreshold: 15,
    criticalThreshold: 25,
    enabled: true
  },
  {
    id: 116,
    code: 'OPS_TEAM_006',
    name: 'Average Crew Experience Level',
    description: 'Average years of experience across crew',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'COUNT',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'users', fields: ['years_experience'] }],
    calculation: 'AVG(years_experience)',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 117,
    code: 'OPS_TEAM_007',
    name: 'Staff Communication Response Time',
    description: 'Average time for staff to respond to messages',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'HOURS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['sent_at', 'read_at'] }],
    calculation: 'AVG(read_at - sent_at)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 118,
    code: 'OPS_TEAM_008',
    name: 'Incident Report Frequency',
    description: 'Safety incidents per event or per 1000 staff hours',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'RATE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'incidents', fields: ['id'] },
      { table: 'time_entries', fields: ['duration_minutes'] }
    ],
    calculation: 'COUNT(incidents) / (Total Hours / 1000)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 119,
    code: 'OPS_TEAM_009',
    name: 'Staff Punctuality Rate',
    description: 'Percentage of staff arrivals that were on time',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'staff_assignments', fields: ['scheduled_start', 'actual_start'] }],
    calculation: '(On-time Arrivals / Total Scheduled Arrivals) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    targetValue: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    enabled: true
  },
  {
    id: 120,
    code: 'OPS_TEAM_010',
    name: 'Certification Compliance Rate',
    description: 'Percentage of staff with all required certifications valid',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'users', fields: ['certifications'] },
      { table: 'staff_positions', fields: ['required_certifications'] }
    ],
    calculation: '(Staff with Valid Certs / Total Staff) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE'],
    targetValue: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    enabled: true
  },
  {
    id: 121,
    code: 'OPS_TEAM_011',
    name: 'Overtime Percentage',
    description: 'Percentage of hours worked that were overtime',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'time_entries', fields: ['work_type', 'duration_minutes'] },
      { table: 'staff_assignments', fields: ['overtime_hours'] }
    ],
    calculation: '(Overtime Hours / Total Hours) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    warningThreshold: 15,
    criticalThreshold: 25,
    enabled: true
  },
  {
    id: 122,
    code: 'OPS_TEAM_012',
    name: 'Staff Productivity Score',
    description: 'Tasks completed per staff member per day',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['task_status', 'assigned_to_user_id'] }],
    calculation: 'Total Completed Tasks / (Staff Count × Days)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'BAR_CHART'],
    enabled: true
  },
  {
    id: 123,
    code: 'OPS_TEAM_013',
    name: 'Team Collaboration Score',
    description: 'Percentage of tasks requiring collaboration completed successfully',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tasks', fields: ['task_status', 'assigned_to_user_id'] }],
    calculation: '(Collaborative Tasks Completed / Total Collaborative Tasks) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 124,
    code: 'OPS_TEAM_014',
    name: 'Staff Retention Rate',
    description: 'Percentage of staff returning for subsequent events',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'staff_assignments', fields: ['user_id', 'event_id'] }],
    calculation: '(Returning Staff / Total Previous Staff) × 100',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 125,
    code: 'OPS_TEAM_015',
    name: 'Skills Gap Index',
    description: 'Percentage of required skills not covered by current staff',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'staff_positions', fields: ['required_skills'] },
      { table: 'users', fields: ['specialization'] }
    ],
    calculation: '(Uncovered Skills / Total Required Skills) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 126,
    code: 'OPS_TEAM_016',
    name: 'Onboarding Completion Time',
    description: 'Average days to complete new staff onboarding',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'user_organizations', fields: ['invited_at', 'joined_at'] }],
    calculation: 'AVG(onboarding_complete_date - hired_date)',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 127,
    code: 'OPS_TEAM_017',
    name: 'Performance Review Completion',
    description: 'Percentage of scheduled performance reviews completed',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'users', fields: ['metadata'] }],
    calculation: '(Reviews Completed / Reviews Scheduled) × 100',
    updateFrequency: 'QUARTERLY',
    visualizations: ['GAUGE'],
    targetValue: 100,
    enabled: true
  },
  {
    id: 128,
    code: 'OPS_TEAM_018',
    name: 'Staff Morale Index',
    description: 'Composite score from multiple staff satisfaction indicators',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['satisfaction_rating'] }],
    calculation: 'Weighted average of components',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE', 'TREND_INDICATOR'],
    enabled: true
  },
  {
    id: 129,
    code: 'OPS_TEAM_019',
    name: 'Internal Promotion Rate',
    description: 'Percentage of positions filled by internal candidates',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'PERCENTAGE',
    targetDirection: 'TARGET_RANGE',
    dataSources: [{ table: 'user_organizations', fields: ['role', 'updated_at'] }],
    calculation: '(Internal Promotions / Total Promotions) × 100',
    updateFrequency: 'QUARTERLY',
    visualizations: ['GAUGE'],
    targetValue: 50,
    enabled: true
  },
  {
    id: 130,
    code: 'OPS_TEAM_020',
    name: 'Staff Conflict Resolution Time',
    description: 'Average time to resolve staff conflicts or issues',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'TEAM_PERFORMANCE',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['created_at', 'resolved_at'] }],
    calculation: 'AVG(resolution_date - reported_date)',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  // Vendor & Supply Chain (131-145)
  {
    id: 131,
    code: 'OPS_VENDOR_001',
    name: 'Vendor Reliability Score',
    description: 'Percentage of on-time vendor deliveries',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendor_deliverables', fields: ['due_date', 'delivered_at'] }],
    calculation: '(On-time Deliveries / Total Deliveries) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'BAR_CHART'],
    targetValue: 95,
    warningThreshold: 90,
    criticalThreshold: 85,
    enabled: true
  },
  {
    id: 132,
    code: 'OPS_VENDOR_002',
    name: 'Supplier Lead Time',
    description: 'Average days from order to delivery',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'vendor_deliverables', fields: ['requested_at', 'delivered_at'] }],
    calculation: 'AVG(delivered_at - requested_at)',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'BAR_CHART'],
    enabled: true
  },
  {
    id: 133,
    code: 'OPS_VENDOR_003',
    name: 'Contract Compliance Rate',
    description: 'Percentage of contracts meeting all stated terms',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'contracts', fields: ['contract_status'] }],
    calculation: '(Compliant Contracts / Total Active Contracts) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE'],
    targetValue: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    enabled: true
  },
  {
    id: 134,
    code: 'OPS_VENDOR_004',
    name: 'Vendor Cost Variance',
    description: 'Percentage difference between budgeted and actual vendor costs',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'TARGET_RANGE',
    dataSources: [{ table: 'budget_line_items', fields: ['budgeted_amount', 'actual_amount'] }],
    calculation: '((Actual - Budgeted) / Budgeted) × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER', 'BAR_CHART'],
    targetValue: 0,
    warningThreshold: 10,
    criticalThreshold: 20,
    enabled: true
  },
  {
    id: 135,
    code: 'OPS_VENDOR_005',
    name: 'Quality Rejection Rate',
    description: 'Percentage of vendor deliverables rejected for quality issues',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'vendor_deliverables', fields: ['deliverable_status'] }],
    calculation: '(Rejected Deliverables / Total Deliverables) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    warningThreshold: 5,
    criticalThreshold: 10,
    enabled: true
  },
  {
    id: 136,
    code: 'OPS_VENDOR_006',
    name: 'Backup Vendor Activation Rate',
    description: 'Number of times backup vendors were needed',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'COUNT',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['is_backup', 'metadata'] }],
    calculation: 'COUNT(backup activations)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 137,
    code: 'OPS_VENDOR_007',
    name: 'Vendor Dispute Resolution Time',
    description: 'Average days to resolve vendor disputes',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'DAYS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'communications', fields: ['created_at', 'resolved_at'] }],
    calculation: 'AVG(resolution_date - dispute_raised_date)',
    updateFrequency: 'MONTHLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 138,
    code: 'OPS_VENDOR_008',
    name: 'Local Vendor Percentage',
    description: 'Percentage of vendors sourced locally',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['city', 'state'] }],
    calculation: '(Local Vendors / Total Vendors) × 100',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['GAUGE', 'PIE_CHART'],
    enabled: true
  },
  {
    id: 139,
    code: 'OPS_VENDOR_009',
    name: 'Sustainable Supplier Percentage',
    description: 'Percentage of vendors with sustainability certifications',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['metadata'] }],
    calculation: '(Certified Sustainable Vendors / Total Vendors) × 100',
    updateFrequency: 'QUARTERLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 140,
    code: 'OPS_VENDOR_010',
    name: 'Vendor NPS',
    description: 'Likelihood of recommending vendor to others',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['quality_rating'] }],
    calculation: '(% Promoters - % Detractors)',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['NUMBER', 'BAR_CHART'],
    targetValue: 50,
    warningThreshold: 30,
    criticalThreshold: 10,
    enabled: true
  },
  {
    id: 141,
    code: 'OPS_VENDOR_011',
    name: 'Vendor Response Time',
    description: 'Average time for vendors to respond to requests/inquiries',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'HOURS',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'communications', fields: ['created_at', 'read_at'] },
      { table: 'vendor_deliverables', fields: ['requested_at'] }
    ],
    calculation: 'AVG(response_time - request_time)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 142,
    code: 'OPS_VENDOR_012',
    name: 'Vendor Performance Score',
    description: 'Composite score of quality, reliability, and cost metrics',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['quality_rating', 'reliability_rating'] }],
    calculation: 'Weighted average of component scores',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 143,
    code: 'OPS_VENDOR_013',
    name: 'Contract Renewal Rate',
    description: 'Percentage of expiring contracts that were renewed',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'PERCENTAGE',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'contracts', fields: ['expiration_date', 'contract_status'] }],
    calculation: '(Renewed Contracts / Expiring Contracts) × 100',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 144,
    code: 'OPS_VENDOR_014',
    name: 'Vendor Diversity Index',
    description: 'Measure of diversity across vendor portfolio',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'INDEX',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'vendors', fields: ['vendor_type', 'metadata'] }],
    calculation: 'Diversity calculation across categories',
    updateFrequency: 'QUARTERLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 145,
    code: 'OPS_VENDOR_015',
    name: 'Supply Chain Risk Score',
    description: 'Assessment of supply chain vulnerabilities',
    category: 'OPERATIONAL_EFFICIENCY',
    subcategory: 'VENDOR_SUPPLY_CHAIN',
    unit: 'SCORE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [
      { table: 'vendors', fields: ['is_backup', 'reliability_rating'] },
      { table: 'contracts', fields: ['contract_status'] }
    ],
    calculation: 'Risk scoring algorithm',
    updateFrequency: 'MONTHLY',
    visualizations: ['GAUGE'],
    warningThreshold: 40,
    criticalThreshold: 60,
    enabled: true
  }
];
