/**
 * MARKETING & AUDIENCE ENGAGEMENT KPIs (146-175)
 * Digital Marketing (146-155), Audience Insights (156-165), Brand & Experience (166-175)
 */

import type { KPIDefinition } from './types/kpi-types';

export const MARKETING_KPIS: KPIDefinition[] = [
  // Digital Marketing (146-155)
  {
    id: 146,
    code: 'MKT_DIG_001',
    name: 'Social Media Engagement Rate',
    description: 'Total interactions divided by total impressions',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'social_media_posts', fields: ['likes', 'comments', 'shares', 'impressions'] }],
    calculation: '(SUM(likes + comments + shares) / SUM(impressions)) × 100',
    updateFrequency: 'HOURLY',
    visualizations: ['LINE_CHART', 'GAUGE'],
    targetValue: 3.5,
    warningThreshold: 2,
    criticalThreshold: 1,
    enabled: true
  },
  {
    id: 147,
    code: 'MKT_DIG_002',
    name: 'Website Conversion Rate',
    description: 'Percentage of website visitors who completed desired action',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'analytics_events', fields: ['event_name', 'user_id'] }],
    calculation: '(Conversions / Total Visitors) × 100',
    updateFrequency: 'HOURLY',
    visualizations: ['GAUGE', 'FUNNEL'],
    enabled: true
  },
  {
    id: 148,
    code: 'MKT_DIG_003',
    name: 'Landing Page Bounce Rate',
    description: 'Percentage of single-page sessions',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'LOWER_IS_BETTER',
    dataSources: [{ table: 'analytics_events', fields: ['session_id', 'page_url'] }],
    calculation: '(Single Page Sessions / Total Sessions) × 100',
    updateFrequency: 'HOURLY',
    visualizations: ['GAUGE'],
    warningThreshold: 60,
    criticalThreshold: 75,
    enabled: true
  },
  {
    id: 149,
    code: 'MKT_DIG_004',
    name: 'Email Campaign Click-Through Rate',
    description: 'Percentage of email recipients who clicked links',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'email_campaigns', fields: ['emails_clicked', 'emails_delivered'] }],
    calculation: '(SUM(emails_clicked) / SUM(emails_delivered)) × 100',
    updateFrequency: 'HOURLY',
    visualizations: ['GAUGE', 'BAR_CHART'],
    targetValue: 3.5,
    warningThreshold: 2,
    criticalThreshold: 1,
    enabled: true
  },
  {
    id: 150,
    code: 'MKT_DIG_005',
    name: 'Email Open Rate',
    description: 'Percentage of delivered emails that were opened',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'email_campaigns', fields: ['emails_opened', 'emails_delivered'] }],
    calculation: '(SUM(emails_opened) / SUM(emails_delivered)) × 100',
    updateFrequency: 'HOURLY',
    visualizations: ['GAUGE', 'LINE_CHART'],
    targetValue: 20,
    warningThreshold: 15,
    criticalThreshold: 10,
    enabled: true
  },
  {
    id: 151,
    code: 'MKT_DIG_006',
    name: 'Email List Growth Rate',
    description: 'Net new subscribers as percentage of total list',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'email_campaigns', fields: ['subscriber_count'] }],
    calculation: '((New Subscribers - Unsubscribes) / Total Subscribers) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['LINE_CHART'],
    enabled: true
  },
  {
    id: 152,
    code: 'MKT_DIG_007',
    name: 'Social Media Follower Growth',
    description: 'Net new followers gained in period',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'social_media_posts', fields: ['follower_count'] }],
    calculation: '(New Followers - Unfollows) / Previous Total × 100',
    updateFrequency: 'DAILY',
    visualizations: ['LINE_CHART'],
    enabled: true
  },
  {
    id: 153,
    code: 'MKT_DIG_008',
    name: 'Paid Ad ROAS',
    description: 'Revenue generated per dollar spent on paid advertising',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'RATIO',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'marketing_campaigns', fields: ['actual_spend', 'actual_revenue'] }],
    calculation: 'Revenue from Ads / Ad Spend',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    targetValue: 3,
    warningThreshold: 2,
    criticalThreshold: 1,
    enabled: true
  },
  {
    id: 154,
    code: 'MKT_DIG_009',
    name: 'Organic Search Traffic Percentage',
    description: 'Percentage of website traffic from organic search',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'analytics_events', fields: ['utm_source', 'utm_medium'] }],
    calculation: '(Organic Traffic / Total Traffic) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['PIE_CHART', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 155,
    code: 'MKT_DIG_010',
    name: 'Video View Completion Rate',
    description: 'Percentage of video viewers who watched to end',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'DIGITAL_MARKETING',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'analytics_events', fields: ['event_name', 'properties'] }],
    calculation: '(Completed Views / Total Views) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  // Audience Insights (156-165)
  {
    id: 156,
    code: 'MKT_AUD_001',
    name: 'Net Promoter Score (NPS)',
    description: 'Likelihood of attendees recommending event',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['nps_score'], filters: ['survey_type = nps'] }],
    calculation: '(% Promoters [9-10] - % Detractors [0-6])',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['GAUGE', 'DISTRIBUTION'],
    targetValue: 50,
    warningThreshold: 30,
    criticalThreshold: 10,
    enabled: true
  },
  {
    id: 157,
    code: 'MKT_AUD_002',
    name: 'Brand Mention Velocity',
    description: 'Number of brand mentions per day during campaign period',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'brand_mentions', fields: ['mentioned_at'] }],
    calculation: 'COUNT(mentions) / Days in Period',
    updateFrequency: 'DAILY',
    visualizations: ['LINE_CHART'],
    enabled: true
  },
  {
    id: 158,
    code: 'MKT_AUD_003',
    name: 'Audience Demographics Match',
    description: 'Percentage alignment between target and actual demographics',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tickets', fields: ['purchaser_id'] }],
    calculation: 'Demographic overlap calculation',
    updateFrequency: 'WEEKLY',
    visualizations: ['COMPARISON'],
    enabled: true
  },
  {
    id: 159,
    code: 'MKT_AUD_004',
    name: 'Geographic Reach Diversity',
    description: 'Number of different regions/countries represented',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'tickets', fields: ['billing_city', 'billing_state', 'billing_country'] }],
    calculation: 'COUNT(DISTINCT geographic_units)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'HEATMAP'],
    enabled: true
  },
  {
    id: 160,
    code: 'MKT_AUD_005',
    name: 'Age Distribution Index',
    description: 'Breakdown of attendees by age group',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'PERCENTAGE',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'users', fields: ['date_of_birth'] }],
    calculation: 'COUNT per age group / Total × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['BAR_CHART', 'PIE_CHART'],
    enabled: true
  },
  {
    id: 161,
    code: 'MKT_AUD_006',
    name: 'Gender Distribution',
    description: 'Gender breakdown of attendees',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'PERCENTAGE',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'users', fields: ['metadata'] }],
    calculation: 'COUNT per gender / Total × 100',
    updateFrequency: 'WEEKLY',
    visualizations: ['PIE_CHART'],
    enabled: true
  },
  {
    id: 162,
    code: 'MKT_AUD_007',
    name: 'Income Bracket Distribution',
    description: 'Economic demographics of attendees',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'PERCENTAGE',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'survey_responses', fields: ['income_bracket'] }],
    calculation: 'COUNT per bracket / Total × 100',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['BAR_CHART'],
    enabled: true
  },
  {
    id: 163,
    code: 'MKT_AUD_008',
    name: 'Interest Affinity Score',
    description: 'Alignment between event type and attendee interests',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'users', fields: ['interests'] }],
    calculation: 'Interest matching algorithm',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 164,
    code: 'MKT_AUD_009',
    name: 'Event Discovery Method',
    description: 'How attendees found out about the event',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'PERCENTAGE',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'analytics_events', fields: ['utm_source', 'utm_medium', 'referrer'] }],
    calculation: 'COUNT per channel / Total × 100',
    updateFrequency: 'DAILY',
    visualizations: ['PIE_CHART', 'BAR_CHART'],
    enabled: true
  },
  {
    id: 165,
    code: 'MKT_AUD_010',
    name: 'First-Time vs Repeat Ratio',
    description: 'Proportion of new attendees to returning attendees',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'AUDIENCE_INSIGHTS',
    unit: 'RATIO',
    targetDirection: 'INFORMATIONAL',
    dataSources: [{ table: 'tickets', fields: ['purchaser_id'] }],
    calculation: 'New Attendees : Repeat Attendees',
    updateFrequency: 'DAILY',
    visualizations: ['PIE_CHART'],
    enabled: true
  },
  // Brand & Experience (166-175)
  {
    id: 166,
    code: 'MKT_BRAND_001',
    name: 'Brand Awareness Lift',
    description: 'Increase in brand recognition post-event vs pre-event',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['brand_awareness'] }],
    calculation: 'Post-Event Awareness % - Pre-Event Awareness %',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['COMPARISON'],
    enabled: true
  },
  {
    id: 167,
    code: 'MKT_BRAND_002',
    name: 'Brand Sentiment Score',
    description: 'Ratio of positive to total brand mentions',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'brand_mentions', fields: ['sentiment'] }],
    calculation: '(Positive Mentions / Total Mentions) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE', 'LINE_CHART'],
    targetValue: 70,
    warningThreshold: 50,
    criticalThreshold: 30,
    enabled: true
  },
  {
    id: 168,
    code: 'MKT_BRAND_003',
    name: 'User-Generated Content Volume',
    description: 'Number of fan-created posts, photos, videos about event',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'brand_mentions', fields: ['mention_type'] }],
    calculation: 'COUNT(user_generated_content)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    enabled: true
  },
  {
    id: 169,
    code: 'MKT_BRAND_004',
    name: 'Hashtag Performance',
    description: 'Unique uses of official event hashtag',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'social_media_posts', fields: ['hashtags'] }],
    calculation: 'COUNT(DISTINCT hashtag uses)',
    updateFrequency: 'HOURLY',
    visualizations: ['NUMBER', 'TREND_INDICATOR'],
    enabled: true
  },
  {
    id: 170,
    code: 'MKT_BRAND_005',
    name: 'Media Impressions',
    description: 'Total reach through PR and media coverage',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'COUNT',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'brand_mentions', fields: ['reach'] }],
    calculation: 'SUM(article reach + broadcast viewers)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'BAR_CHART'],
    enabled: true
  },
  {
    id: 171,
    code: 'MKT_BRAND_006',
    name: 'Press Mention Sentiment',
    description: 'Percentage of positive press coverage',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'brand_mentions', fields: ['sentiment', 'source_type'] }],
    calculation: '(Positive Articles / Total Articles) × 100',
    updateFrequency: 'DAILY',
    visualizations: ['GAUGE'],
    enabled: true
  },
  {
    id: 172,
    code: 'MKT_BRAND_007',
    name: 'Partnership Brand Lift',
    description: 'Increase in sponsor/partner brand awareness from event association',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'PERCENTAGE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'survey_responses', fields: ['sponsor_awareness'] }],
    calculation: 'Post-event awareness increase for sponsors',
    updateFrequency: 'AFTER_EVENT',
    visualizations: ['BAR_CHART'],
    enabled: true
  },
  {
    id: 173,
    code: 'MKT_BRAND_008',
    name: 'Event FOMO Factor',
    description: 'Indicator of demand exceeding supply',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'SCORE',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'tickets', fields: ['metadata'] },
      { table: 'brand_mentions', fields: ['content'] }
    ],
    calculation: 'Composite of multiple demand indicators',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 174,
    code: 'MKT_BRAND_009',
    name: 'Post-Event Engagement Duration',
    description: 'Days of continued social engagement after event',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'DAYS',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [
      { table: 'social_media_posts', fields: ['post_date'] },
      { table: 'brand_mentions', fields: ['mentioned_at'] }
    ],
    calculation: 'Days until engagement drops below threshold',
    updateFrequency: 'WEEKLY',
    visualizations: ['NUMBER'],
    enabled: true
  },
  {
    id: 175,
    code: 'MKT_BRAND_010',
    name: 'Content Virality Coefficient',
    description: 'Average shares per original post',
    category: 'MARKETING_ENGAGEMENT',
    subcategory: 'BRAND_EXPERIENCE',
    unit: 'RATIO',
    targetDirection: 'HIGHER_IS_BETTER',
    dataSources: [{ table: 'social_media_posts', fields: ['shares', 'id'] }],
    calculation: 'AVG(shares / original posts)',
    updateFrequency: 'DAILY',
    visualizations: ['NUMBER', 'LINE_CHART'],
    targetValue: 1,
    enabled: true
  }
];
