-- 0033_seed_200_kpi_reports.sql
-- Seeds all 200 global KPI reports for the GVTEWAY platform

DO $$
DECLARE
  v_org_id uuid;
BEGIN
  SELECT id INTO v_org_id FROM organizations LIMIT 1;
  IF v_org_id IS NULL THEN
    INSERT INTO organizations (name, slug) VALUES ('System', 'system') RETURNING id INTO v_org_id;
  END IF;

  -- Delete existing global reports to avoid duplicates
  DELETE FROM kpi_reports WHERE is_global = true;

  -- FINANCIAL PERFORMANCE KPIs (1-45)
  INSERT INTO kpi_reports (organization_id, name, description, kpi_codes, category, is_global) VALUES
  (v_org_id, 'Total Event Revenue', 'Sum of all revenue streams for an event', '{FIN_REV_001}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Per Capita Spending', 'Average revenue generated per attendee', '{FIN_REV_002}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'VIP/Premium Revenue', 'Revenue from VIP packages and premium experiences', '{FIN_REV_003}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Merchandise Revenue', 'Total merchandise sales revenue', '{FIN_REV_004}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'F&B Revenue', 'Food and beverage sales revenue', '{FIN_REV_005}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Parking Revenue', 'Revenue from parking fees', '{FIN_REV_006}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Sponsorship Revenue', 'Total sponsorship and partnership revenue', '{FIN_REV_007}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Secondary Ticket Revenue', 'Revenue from resale marketplace', '{FIN_REV_008}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Early Bird Revenue', 'Revenue from early bird ticket sales', '{FIN_REV_009}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Group Sales Revenue', 'Revenue from group ticket packages', '{FIN_REV_010}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Cost Per Attendee', 'Total event costs divided by attendance', '{FIN_COST_001}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Labor Cost Percentage', 'Labor costs as percentage of total budget', '{FIN_COST_002}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Vendor Cost Ratio', 'Third-party vendor costs vs total costs', '{FIN_COST_003}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Marketing Cost Per Ticket', 'Marketing spend divided by tickets sold', '{FIN_COST_004}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Venue Rental Cost', 'Total venue rental and facility costs', '{FIN_COST_005}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Equipment Rental Cost', 'Audio, visual, and staging equipment costs', '{FIN_COST_006}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Insurance Cost', 'Event insurance and liability costs', '{FIN_COST_007}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Security Cost', 'Security personnel and services costs', '{FIN_COST_008}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Technology Cost', 'Ticketing, streaming, and tech infrastructure costs', '{FIN_COST_009}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Logistics Cost', 'Transportation, shipping, and logistics costs', '{FIN_COST_010}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Budget Variance', 'Difference between budgeted and actual costs', '{FIN_COST_011}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Cost Overrun Rate', 'Percentage of budget categories exceeding plan', '{FIN_COST_012}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Contingency Usage', 'Percentage of contingency budget utilized', '{FIN_COST_013}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Burn Rate', 'Rate of budget consumption over time', '{FIN_COST_014}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Cost Savings Achieved', 'Savings from negotiations and efficiencies', '{FIN_COST_015}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Profit Margin', 'Net profit as percentage of revenue', '{FIN_PROF_001}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Gross Profit', 'Revenue minus direct costs', '{FIN_PROF_002}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Net Profit', 'Total profit after all expenses', '{FIN_PROF_003}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'EBITDA', 'Earnings before interest, taxes, depreciation, amortization', '{FIN_PROF_004}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Operating Profit Margin', 'Operating income as percentage of revenue', '{FIN_PROF_005}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Return on Investment', 'Net profit divided by total investment', '{FIN_PROF_006}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Return on Assets', 'Net income relative to total assets used', '{FIN_PROF_007}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Break-Even Point', 'Attendance/revenue needed to cover costs', '{FIN_PROF_008}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Contribution Margin', 'Revenue minus variable costs per unit', '{FIN_PROF_009}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Economic Value Added', 'Net operating profit minus capital costs', '{FIN_PROF_010}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Cash Flow from Operations', 'Net cash generated from event operations', '{FIN_PROF_011}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Working Capital Ratio', 'Current assets vs current liabilities', '{FIN_PROF_012}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Days Sales Outstanding', 'Average days to collect receivables', '{FIN_PROF_013}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Accounts Payable Turnover', 'Rate of paying vendor invoices', '{FIN_PROF_014}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Revenue Per Available Seat', 'Total revenue divided by venue capacity', '{FIN_PROF_015}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Revenue Per Square Foot', 'Revenue relative to venue space utilized', '{FIN_PROF_016}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Revenue Growth Rate', 'Year-over-year revenue increase percentage', '{FIN_PROF_017}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Profit Per Event', 'Average net profit per event produced', '{FIN_PROF_018}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Revenue Multiple', 'Total revenue relative to production costs', '{FIN_PROF_019}', 'FINANCIAL_PERFORMANCE', true),
  (v_org_id, 'Asset Turnover Ratio', 'Revenue generated per dollar of assets', '{FIN_PROF_020}', 'FINANCIAL_PERFORMANCE', true);

  -- TICKET & ATTENDANCE KPIs (46-90)
  INSERT INTO kpi_reports (organization_id, name, description, kpi_codes, category, is_global) VALUES
  (v_org_id, 'Total Tickets Sold', 'Count of all tickets sold for event', '{TKT_SALES_001}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Sell-Through Rate', 'Percentage of available tickets sold', '{TKT_SALES_002}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Average Ticket Price', 'Mean price across all ticket types', '{TKT_SALES_003}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Ticket Revenue', 'Total revenue from ticket sales', '{TKT_SALES_004}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Sales Velocity', 'Tickets sold per day/hour', '{TKT_SALES_005}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Channel Mix', 'Distribution of sales across channels', '{TKT_SALES_006}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Mobile Sales Percentage', 'Tickets purchased via mobile devices', '{TKT_SALES_007}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Conversion Rate', 'Visitors who complete ticket purchase', '{TKT_SALES_008}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Cart Abandonment Rate', 'Started but incomplete purchases', '{TKT_SALES_009}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Promo Code Usage', 'Percentage of sales using promotions', '{TKT_SALES_010}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Refund Rate', 'Percentage of tickets refunded', '{TKT_SALES_011}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Chargeback Rate', 'Disputed transactions percentage', '{TKT_SALES_012}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Season Pass Sales', 'Multi-event package sales', '{TKT_SALES_013}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Upgrade Rate', 'Attendees upgrading ticket tier', '{TKT_SALES_014}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Add-On Attachment Rate', 'Tickets with additional purchases', '{TKT_SALES_015}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'First-Time Buyer Rate', 'New customers as percentage of sales', '{TKT_SALES_016}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Repeat Purchase Rate', 'Returning customers percentage', '{TKT_SALES_017}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Days to Sellout', 'Time from on-sale to capacity', '{TKT_SALES_018}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Waitlist Conversion', 'Waitlist members who purchased', '{TKT_SALES_019}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Presale Performance', 'Presale vs general sale ratio', '{TKT_SALES_020}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Last-Minute Sales', 'Tickets sold in final 48 hours', '{TKT_SALES_021}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Geographic Distribution', 'Sales by region/market', '{TKT_SALES_022}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Payment Method Mix', 'Distribution of payment types', '{TKT_SALES_023}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Average Order Value', 'Mean transaction amount', '{TKT_SALES_024}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Tickets Per Transaction', 'Average tickets per order', '{TKT_SALES_025}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Venue Capacity Utilization', 'Actual attendance vs capacity', '{TKT_CAP_001}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Section Fill Rate', 'Occupancy by venue section', '{TKT_CAP_002}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'No-Show Rate', 'Ticket holders who did not attend', '{TKT_CAP_003}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Check-In Rate', 'Percentage of tickets scanned', '{TKT_CAP_004}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Peak Attendance Time', 'Highest concurrent attendance', '{TKT_CAP_005}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Entry Flow Rate', 'Attendees processed per hour', '{TKT_CAP_006}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Exit Flow Rate', 'Departure rate post-event', '{TKT_CAP_007}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Dwell Time', 'Average time spent at venue', '{TKT_CAP_008}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Zone Density', 'Crowd density by area', '{TKT_CAP_009}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Accessibility Utilization', 'ADA seating/services usage', '{TKT_CAP_010}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'VIP Area Utilization', 'Premium section occupancy', '{TKT_CAP_011}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Standing vs Seated Ratio', 'GA vs reserved attendance', '{TKT_CAP_012}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Multi-Day Attendance', 'Unique vs repeat daily attendance', '{TKT_CAP_013}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Weather Impact Factor', 'Attendance variance due to weather', '{TKT_CAP_014}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Competitor Event Impact', 'Effect of competing events', '{TKT_CAP_015}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Dynamic Pricing Lift', 'Revenue increase from dynamic pricing', '{TKT_PRICE_001}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Price Elasticity', 'Demand sensitivity to price changes', '{TKT_PRICE_002}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Tier Distribution', 'Sales across price tiers', '{TKT_PRICE_003}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Discount Depth', 'Average discount percentage applied', '{TKT_PRICE_004}', 'TICKET_ATTENDANCE', true),
  (v_org_id, 'Revenue Per Available Ticket', 'Total revenue divided by capacity', '{TKT_PRICE_005}', 'TICKET_ATTENDANCE', true);

  -- OPERATIONAL EFFICIENCY KPIs (91-145)
  INSERT INTO kpi_reports (organization_id, name, description, kpi_codes, category, is_global) VALUES
  (v_org_id, 'Schedule Adherence Rate', 'Milestones completed on time', '{OPS_PM_001}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Project Timeline Adherence', 'Project staying on schedule', '{OPS_PM_002}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Change Order Frequency', 'Scope changes per project', '{OPS_PM_003}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Risk Mitigation Success', 'Risks successfully prevented', '{OPS_PM_004}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Milestone Velocity', 'Days ahead/behind schedule', '{OPS_PM_005}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Resource Allocation Efficiency', 'Allocated vs utilized hours', '{OPS_PM_006}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Dependency Fulfillment', 'Task dependencies met on time', '{OPS_PM_007}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Critical Path Variance', 'Critical path timeline deviation', '{OPS_PM_008}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Average Task Duration', 'Mean time to complete tasks', '{OPS_PM_009}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Sprint Velocity', 'Story points per sprint', '{OPS_PM_010}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Blocker Resolution Time', 'Time to clear blockers', '{OPS_PM_011}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Task Completion Rate', 'Tasks marked complete', '{OPS_PM_012}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Overdue Task Percentage', 'Tasks past due date', '{OPS_PM_013}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Task Estimation Accuracy', 'Estimated vs actual duration', '{OPS_PM_014}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Planning Accuracy', 'Delivery within original plan', '{OPS_PM_015}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Scope Creep Index', 'Scope increase from baseline', '{OPS_PM_016}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Communication Response Time', 'Project communication response', '{OPS_PM_017}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Meeting Effectiveness', 'Meetings with actionable outcomes', '{OPS_PM_018}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Decision Velocity', 'Time from issue to decision', '{OPS_PM_019}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Project Health Score', 'Composite project health', '{OPS_PM_020}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Utilization Rate', 'Billable/productive hours', '{OPS_TEAM_001}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Employee Satisfaction', 'Staff satisfaction rating', '{OPS_TEAM_002}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Training Completion Rate', 'Required training completed', '{OPS_TEAM_003}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Cross-Training Index', 'Roles per staff member', '{OPS_TEAM_004}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Turnover Rate', 'Staff departures percentage', '{OPS_TEAM_005}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Average Crew Experience', 'Years of experience', '{OPS_TEAM_006}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Response Time', 'Message response time', '{OPS_TEAM_007}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Incident Report Frequency', 'Safety incidents per event', '{OPS_TEAM_008}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Punctuality', 'On-time arrivals', '{OPS_TEAM_009}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Certification Compliance', 'Valid certifications', '{OPS_TEAM_010}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Overtime Percentage', 'Overtime hours worked', '{OPS_TEAM_011}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Productivity', 'Tasks per staff per day', '{OPS_TEAM_012}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Team Collaboration Score', 'Collaborative task success', '{OPS_TEAM_013}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Retention Rate', 'Returning staff percentage', '{OPS_TEAM_014}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Skills Gap Index', 'Uncovered required skills', '{OPS_TEAM_015}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Onboarding Time', 'Days to complete onboarding', '{OPS_TEAM_016}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Performance Review Completion', 'Reviews completed on schedule', '{OPS_TEAM_017}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Staff Morale Index', 'Staff satisfaction composite', '{OPS_TEAM_018}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Internal Promotion Rate', 'Internal candidates promoted', '{OPS_TEAM_019}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Conflict Resolution Time', 'Time to resolve conflicts', '{OPS_TEAM_020}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Reliability Score', 'On-time vendor deliveries', '{OPS_VENDOR_001}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Supplier Lead Time', 'Order to delivery time', '{OPS_VENDOR_002}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Contract Compliance Rate', 'Contracts meeting terms', '{OPS_VENDOR_003}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Cost Variance', 'Budget vs actual vendor costs', '{OPS_VENDOR_004}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Quality Rejection Rate', 'Rejected deliverables', '{OPS_VENDOR_005}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Backup Vendor Activation', 'Backup vendor usage', '{OPS_VENDOR_006}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Dispute Resolution', 'Time to resolve disputes', '{OPS_VENDOR_007}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Local Vendor Percentage', 'Locally sourced vendors', '{OPS_VENDOR_008}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Sustainable Supplier Rate', 'Sustainability certified vendors', '{OPS_VENDOR_009}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor NPS', 'Vendor recommendation score', '{OPS_VENDOR_010}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Response Time', 'Vendor inquiry response', '{OPS_VENDOR_011}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Performance Score', 'Composite vendor rating', '{OPS_VENDOR_012}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Contract Renewal Rate', 'Renewed contracts', '{OPS_VENDOR_013}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Vendor Diversity Index', 'Vendor portfolio diversity', '{OPS_VENDOR_014}', 'OPERATIONAL_EFFICIENCY', true),
  (v_org_id, 'Supply Chain Risk Score', 'Supply chain vulnerabilities', '{OPS_VENDOR_015}', 'OPERATIONAL_EFFICIENCY', true);

  -- MARKETING & ENGAGEMENT KPIs (146-175)
  INSERT INTO kpi_reports (organization_id, name, description, kpi_codes, category, is_global) VALUES
  (v_org_id, 'Social Media Engagement', 'Interactions per impressions', '{MKT_DIG_001}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Website Conversion Rate', 'Visitors completing actions', '{MKT_DIG_002}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Landing Page Bounce Rate', 'Single-page sessions', '{MKT_DIG_003}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Email Click-Through Rate', 'Email link clicks', '{MKT_DIG_004}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Email Open Rate', 'Emails opened', '{MKT_DIG_005}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Email List Growth', 'Net new subscribers', '{MKT_DIG_006}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Social Follower Growth', 'Net new followers', '{MKT_DIG_007}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Paid Ad ROAS', 'Ad revenue per dollar spent', '{MKT_DIG_008}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Organic Search Traffic', 'Traffic from organic search', '{MKT_DIG_009}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Video Completion Rate', 'Videos watched to end', '{MKT_DIG_010}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Net Promoter Score', 'Recommendation likelihood', '{MKT_AUD_001}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Brand Mention Velocity', 'Brand mentions per day', '{MKT_AUD_002}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Demographics Match', 'Target vs actual demographics', '{MKT_AUD_003}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Geographic Reach', 'Regions represented', '{MKT_AUD_004}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Age Distribution', 'Attendees by age group', '{MKT_AUD_005}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Gender Distribution', 'Attendee gender breakdown', '{MKT_AUD_006}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Income Distribution', 'Economic demographics', '{MKT_AUD_007}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Interest Affinity', 'Event-interest alignment', '{MKT_AUD_008}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Discovery Method', 'How attendees found event', '{MKT_AUD_009}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'First-Time vs Repeat', 'New vs returning ratio', '{MKT_AUD_010}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Brand Awareness Lift', 'Recognition increase', '{MKT_BRAND_001}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Brand Sentiment Score', 'Positive mention ratio', '{MKT_BRAND_002}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'User-Generated Content', 'Fan-created content volume', '{MKT_BRAND_003}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Hashtag Performance', 'Event hashtag usage', '{MKT_BRAND_004}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Media Impressions', 'PR and media reach', '{MKT_BRAND_005}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Press Sentiment', 'Positive press coverage', '{MKT_BRAND_006}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Partnership Brand Lift', 'Sponsor awareness increase', '{MKT_BRAND_007}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Event FOMO Factor', 'Demand exceeding supply', '{MKT_BRAND_008}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Post-Event Engagement', 'Continued engagement duration', '{MKT_BRAND_009}', 'MARKETING_ENGAGEMENT', true),
  (v_org_id, 'Content Virality', 'Shares per original post', '{MKT_BRAND_010}', 'MARKETING_ENGAGEMENT', true);

  -- CUSTOMER EXPERIENCE KPIs (176-200)
  INSERT INTO kpi_reports (organization_id, name, description, kpi_codes, category, is_global) VALUES
  (v_org_id, 'Overall Satisfaction', 'Event experience rating', '{CX_EXP_001}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Likelihood to Recommend', 'Would recommend event', '{CX_EXP_002}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Expectation Gap', 'Expected vs actual experience', '{CX_EXP_003}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Venue Experience', 'Venue satisfaction rating', '{CX_EXP_004}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Sound Quality', 'Audio experience rating', '{CX_EXP_005}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Visual Production', 'Lighting and visuals rating', '{CX_EXP_006}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'F&B Service Quality', 'Food and beverage rating', '{CX_EXP_007}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Restroom Cleanliness', 'Facilities cleanliness', '{CX_EXP_008}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Parking Experience', 'Parking satisfaction', '{CX_EXP_009}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Accessibility Experience', 'Accessibility accommodations', '{CX_EXP_010}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Merchandise Quality', 'Merchandise satisfaction', '{CX_EXP_011}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Staff Friendliness', 'Staff courtesy rating', '{CX_EXP_012}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Event Flow', 'Pacing and schedule rating', '{CX_EXP_013}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Queue Management', 'Wait times satisfaction', '{CX_EXP_014}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Information Clarity', 'Signage and info clarity', '{CX_EXP_015}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Support Resolution Time', 'Ticket resolution hours', '{CX_SVC_001}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'First Contact Resolution', 'Issues resolved first contact', '{CX_SVC_002}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Complaint Rate', 'Complaints per attendee', '{CX_SVC_003}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Refund Request Rate', 'Refund requests percentage', '{CX_SVC_004}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Support Satisfaction', 'Service interaction rating', '{CX_SVC_005}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Live Chat Response', 'Chat response time', '{CX_SVC_006}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Self-Service Success', 'Self-resolved issues', '{CX_SVC_007}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Escalation Rate', 'Escalated tickets', '{CX_SVC_008}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Follow-Up Completion', 'Required follow-ups done', '{CX_SVC_009}', 'CUSTOMER_EXPERIENCE', true),
  (v_org_id, 'Service Recovery Success', 'Satisfied after resolution', '{CX_SVC_010}', 'CUSTOMER_EXPERIENCE', true);

  RAISE NOTICE 'All 200 KPI Global Reports created successfully';
END $$;
