-- 0108_universal_catalog_items_part3.sql
-- Universal Catalog - Site Infrastructure, Hospitality

-- SITE INFRASTRUCTURE - STRUCTURES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('SITE-001', 'Site Infrastructure', 'Structures', 'Scaffolding', ARRAY['Frame', 'System', 'Rolling'], ARRAY['Planks', 'Guardrails'], 'Height, load capacity', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['scaffolding', 'scaffold'], 50, 200),
('SITE-002', 'Site Infrastructure', 'Structures', 'Bleachers/Grandstand', ARRAY['Portable', 'Fixed', 'VIP'], ARRAY['ADA Access', 'Railings'], 'Capacity, rows', 'Per Seat/Day', 'rental', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['bleachers', 'grandstand'], 5, 25),
('SITE-003', 'Site Infrastructure', 'Structures', 'Observation Tower', ARRAY['Camera', 'Delay', 'Spotlight'], ARRAY['Stairs', 'Platform'], 'Height, platform size', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['tower', 'observation'], 300, 1500),
('SITE-004', 'Site Infrastructure', 'Structures', 'Modular Building', ARRAY['Office', 'Storage', 'Restroom'], ARRAY['HVAC', 'Furniture'], 'Size, amenities', 'Per Unit/Day', 'rental', ARRAY['construction', 'events_entertainment']::industry_vertical[], ARRAY['modular', 'portable'], 200, 1000),
('SITE-005', 'Site Infrastructure', 'Structures', 'Shipping Container', ARRAY['20ft', '40ft', 'Modified'], ARRAY['Locks', 'Ramps'], 'Size, modifications', 'Per Unit/Day', 'rental', ARRAY['construction', 'events_entertainment', 'retail']::industry_vertical[], ARRAY['container', 'storage'], 75, 300)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SITE INFRASTRUCTURE - TENTS
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('TNT-001', 'Site Infrastructure', 'Tents & Canopies', 'Frame Tent', ARRAY['Clear Span', 'Hip End', 'Gable'], ARRAY['Sidewalls', 'Flooring', 'HVAC'], 'Size WxL, peak height', 'Per SqFt/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['tent', 'frame tent'], 1, 5),
('TNT-002', 'Site Infrastructure', 'Tents & Canopies', 'Pole Tent', ARRAY['Center Pole', 'Multi-Pole', 'Sailcloth'], ARRAY['Stakes', 'Sidewalls'], 'Size, pole config', 'Per SqFt/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['pole tent'], 0.75, 3),
('TNT-003', 'Site Infrastructure', 'Tents & Canopies', 'Pop-Up Canopy', ARRAY['10x10', '10x20', 'Custom'], ARRAY['Weights', 'Sidewalls'], 'Size, frame type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'retail', 'sports']::industry_vertical[], ARRAY['pop-up', 'canopy'], 25, 150),
('TNT-004', 'Site Infrastructure', 'Tents & Canopies', 'Stretch Tent', ARRAY['Bedouin', 'Freeform'], ARRAY['Poles', 'Anchoring'], 'Coverage area', 'Per SqFt/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['stretch tent'], 2, 8),
('TNT-005', 'Site Infrastructure', 'Tents & Canopies', 'Geodesic Dome', ARRAY['Event Dome', 'Projection Dome'], ARRAY['Flooring', 'HVAC'], 'Diameter, height', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['dome', 'geodesic'], 500, 5000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SITE INFRASTRUCTURE - FACILITIES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('FAC-001', 'Site Infrastructure', 'Facilities', 'Portable Restroom - Standard', ARRAY['Single', 'Flushable'], ARRAY['Sanitizer', 'Service'], 'Capacity, service', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['restroom', 'portable'], 75, 200),
('FAC-002', 'Site Infrastructure', 'Facilities', 'Portable Restroom - ADA', ARRAY['Wheelchair', 'Family'], ARRAY['Handrails'], 'ADA compliant', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['ADA', 'accessible'], 125, 300),
('FAC-003', 'Site Infrastructure', 'Facilities', 'Restroom Trailer - VIP', ARRAY['2-Station', '4-Station', '8-Station'], ARRAY['Attendant', 'Supplies'], 'Stations, amenities', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['restroom trailer', 'VIP'], 500, 2500),
('FAC-004', 'Site Infrastructure', 'Facilities', 'Shower Trailer', ARRAY['4-Station', '8-Station'], ARRAY['Hot Water', 'Towels'], 'Stations', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['shower', 'trailer'], 400, 1500),
('FAC-005', 'Site Infrastructure', 'Facilities', 'Hand Wash Station', ARRAY['Portable Sink', 'Multi-Station'], ARRAY['Soap', 'Towels'], 'Stations', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction', 'hospitality']::industry_vertical[], ARRAY['hand wash', 'sink'], 50, 200),
('FAC-006', 'Site Infrastructure', 'Facilities', 'Office Trailer', ARRAY['Single Wide', 'Double Wide'], ARRAY['Furniture', 'HVAC'], 'Size, config', 'Per Unit/Day', 'rental', ARRAY['construction', 'events_entertainment', 'film_television']::industry_vertical[], ARRAY['office', 'trailer'], 150, 800),
('FAC-007', 'Site Infrastructure', 'Facilities', 'Green Room/Dressing Room', ARRAY['Star Wagon', 'Trailer', 'Tent'], ARRAY['Furniture', 'Mirrors'], 'Size, amenities', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['green room', 'dressing'], 300, 1500),
('FAC-008', 'Site Infrastructure', 'Facilities', 'First Aid Station', ARRAY['Tent', 'Trailer', 'Container'], ARRAY['Supplies', 'Cots', 'AED'], 'Size, equipment', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction', 'sports']::industry_vertical[], ARRAY['first aid', 'medical'], 200, 1000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- HOSPITALITY - CATERING
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('CAT-001', 'Hospitality', 'Catering', 'Catering Service - Full', ARRAY['Plated', 'Buffet', 'Family Style'], ARRAY['Staff', 'Equipment'], 'Menu, service style', 'Per Person', 'service', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['catering', 'food'], 35, 200),
('CAT-002', 'Hospitality', 'Catering', 'Catering Service - Light', ARRAY['Appetizers', 'Snacks', 'Continental'], ARRAY['Staff', 'Setup'], 'Menu, duration', 'Per Person', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['appetizers', 'snacks'], 15, 50),
('CAT-003', 'Hospitality', 'Catering', 'Food Truck/Mobile Kitchen', ARRAY['Food Truck', 'Trailer', 'Cart'], ARRAY['Generator', 'Supplies'], 'Menu, capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['food truck', 'mobile'], 500, 3000),
('CAT-004', 'Hospitality', 'Catering', 'Commercial Kitchen Rental', ARRAY['Prep Kitchen', 'Full Kitchen'], ARRAY['Equipment', 'Storage'], 'Size, equipment', 'Per Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['kitchen', 'commercial'], 500, 2500),
('CAT-005', 'Hospitality', 'Catering', 'Catering Equipment - Cooking', ARRAY['Oven', 'Grill', 'Fryer', 'Warmer'], ARRAY['Fuel', 'Utensils'], 'Type, capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['cooking', 'oven', 'grill'], 50, 300),
('CAT-006', 'Hospitality', 'Catering', 'Refrigeration', ARRAY['Reach-In', 'Walk-In', 'Cooler Trailer'], ARRAY['Shelving', 'Power'], 'Size, temperature', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['refrigeration', 'cooler'], 75, 500),
('CAT-007', 'Hospitality', 'Catering', 'Chef/Cook', ARRAY['Executive Chef', 'Sous Chef', 'Line Cook'], ARRAY['Uniforms', 'Tools'], 'Experience, cuisine', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['chef', 'cook'], 300, 1500),
('CAT-008', 'Hospitality', 'Catering', 'Catering Staff', ARRAY['Server', 'Busser', 'Captain'], ARRAY['Uniforms'], 'Experience, duties', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['server', 'waiter'], 200, 400)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- HOSPITALITY - BEVERAGE
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('BEV-001', 'Hospitality', 'Beverage', 'Bar Service - Full', ARRAY['Open Bar', 'Cash Bar', 'Limited'], ARRAY['Staff', 'Equipment'], 'Duration, selection', 'Per Person/Hour', 'service', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['bar', 'drinks'], 15, 75),
('BEV-002', 'Hospitality', 'Beverage', 'Bar Service - Non-Alcoholic', ARRAY['Coffee Bar', 'Juice Bar', 'Mocktails'], ARRAY['Staff', 'Equipment'], 'Selection, duration', 'Per Person/Hour', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['non-alcoholic', 'coffee'], 5, 25),
('BEV-003', 'Hospitality', 'Beverage', 'Portable Bar', ARRAY['Standard', 'LED Bar', 'Custom'], ARRAY['Back Bar', 'Stools'], 'Size, style', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['bar', 'portable'], 150, 800),
('BEV-004', 'Hospitality', 'Beverage', 'Draft Beer System', ARRAY['Kegerator', 'Jockey Box', 'Tower'], ARRAY['Kegs', 'CO2'], 'Taps, capacity', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['draft', 'beer', 'keg'], 150, 600),
('BEV-005', 'Hospitality', 'Beverage', 'Coffee Service', ARRAY['Drip', 'Espresso', 'Pour Over'], ARRAY['Cups', 'Condiments'], 'Type, quantity', 'Per Person', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['coffee', 'espresso'], 3, 15),
('BEV-006', 'Hospitality', 'Beverage', 'Bartender', ARRAY['Lead', 'Bartender', 'Barback'], ARRAY['Uniforms', 'Tools'], 'Experience, certs', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['bartender', 'mixologist'], 250, 600)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;
