-- 0109_universal_catalog_items_part4.sql
-- Universal Catalog - Transportation, Safety & Security, Signage, Furniture

-- TRANSPORTATION - VEHICLES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('TRN-001', 'Transportation', 'Vehicles', 'Box Truck', ARRAY['16ft', '24ft', '26ft'], ARRAY['Lift Gate', 'Ramp', 'Pads'], 'Size, lift gate', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'logistics']::industry_vertical[], ARRAY['box truck', 'moving truck'], 150, 400),
('TRN-002', 'Transportation', 'Vehicles', 'Cargo Van', ARRAY['Standard', 'Extended', 'High Roof'], ARRAY['Shelving', 'Dividers'], 'Cargo capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'logistics']::industry_vertical[], ARRAY['cargo van', 'sprinter'], 100, 250),
('TRN-003', 'Transportation', 'Vehicles', 'Flatbed Truck', ARRAY['Standard', 'Lowboy', 'Step Deck'], ARRAY['Straps', 'Tarps'], 'Length, capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction', 'logistics']::industry_vertical[], ARRAY['flatbed', 'truck'], 200, 600),
('TRN-004', 'Transportation', 'Vehicles', 'Tractor Trailer', ARRAY['Dry Van', 'Reefer', 'Flatbed'], ARRAY['Driver', 'Straps'], 'Length, type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'logistics']::industry_vertical[], ARRAY['semi', 'trailer', '18-wheeler'], 400, 1200),
('TRN-005', 'Transportation', 'Vehicles', 'Forklift', ARRAY['Standard', 'Rough Terrain', 'Telehandler'], ARRAY['Attachments', 'Fuel'], 'Capacity, lift height', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction', 'logistics']::industry_vertical[], ARRAY['forklift', 'lift'], 150, 500),
('TRN-006', 'Transportation', 'Vehicles', 'Golf Cart/Utility Vehicle', ARRAY['2-Seat', '4-Seat', '6-Seat', 'Utility'], ARRAY['Charger', 'Enclosure'], 'Passengers, cargo', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['golf cart', 'UTV', 'gator'], 75, 250),
('TRN-007', 'Transportation', 'Vehicles', 'Passenger Van', ARRAY['12-Passenger', '15-Passenger'], ARRAY['Driver'], 'Passengers', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['passenger van', 'shuttle'], 150, 350),
('TRN-008', 'Transportation', 'Vehicles', 'Bus/Coach', ARRAY['Mini Bus', 'Charter Bus', 'Double Decker'], ARRAY['Driver', 'WiFi'], 'Passengers, amenities', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['bus', 'coach', 'charter'], 500, 2500),
('TRN-009', 'Transportation', 'Vehicles', 'Scissor Lift', ARRAY['Electric', 'Rough Terrain'], ARRAY['Harness', 'Outriggers'], 'Height, capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['scissor lift', 'aerial'], 150, 400),
('TRN-010', 'Transportation', 'Vehicles', 'Boom Lift', ARRAY['Articulating', 'Telescopic'], ARRAY['Harness', 'Outriggers'], 'Height, reach', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['boom lift', 'cherry picker'], 250, 800),
('TRN-011', 'Transportation', 'Vehicles', 'Driver/Operator', ARRAY['CDL Driver', 'Forklift Op', 'Cart Driver'], ARRAY['License', 'Certs'], 'License class', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'logistics']::industry_vertical[], ARRAY['driver', 'operator'], 250, 500)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SAFETY & SECURITY - PERSONNEL
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('SEC-001', 'Safety & Security', 'Security Personnel', 'Security Guard - Unarmed', ARRAY['Static Post', 'Roving', 'Supervisor'], ARRAY['Radio', 'Uniform'], 'Licensed, experience', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['security', 'guard', 'unarmed'], 20, 40),
('SEC-002', 'Safety & Security', 'Security Personnel', 'Security Guard - Armed', ARRAY['Armed Guard', 'Executive Protection'], ARRAY['Radio', 'Uniform', 'Weapon'], 'Licensed, certified', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['security', 'armed', 'protection'], 35, 75),
('SEC-003', 'Safety & Security', 'Security Personnel', 'Crowd Management', ARRAY['Crowd Control', 'Line Management', 'Pit Security'], ARRAY['Radio', 'Vest'], 'Experience, training', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['crowd', 'management', 'control'], 20, 35),
('SEC-004', 'Safety & Security', 'Security Personnel', 'Security Director', ARRAY['Security Manager', 'Site Lead'], ARRAY['Radio', 'Laptop'], 'Experience, planning', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['security director', 'manager'], 500, 1200),
('SEC-005', 'Safety & Security', 'Security Personnel', 'Off-Duty Police', ARRAY['Police Officer', 'Sheriff Deputy'], ARRAY['Radio', 'Vehicle'], 'Jurisdiction, authority', 'Per Person/Hour', 'labor', ARRAY['events_entertainment']::industry_vertical[], ARRAY['police', 'law enforcement'], 50, 100)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SAFETY & SECURITY - EQUIPMENT
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('SEC-010', 'Safety & Security', 'Security Equipment', 'Metal Detector - Walk Through', ARRAY['Standard', 'Multi-Zone'], ARRAY['Tables', 'Bins'], 'Sensitivity, zones', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['metal detector', 'screening'], 150, 400),
('SEC-011', 'Safety & Security', 'Security Equipment', 'Metal Detector - Handheld', ARRAY['Wand', 'Scanner'], ARRAY['Charger', 'Holster'], 'Sensitivity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['wand', 'handheld', 'scanner'], 15, 50),
('SEC-012', 'Safety & Security', 'Security Equipment', 'X-Ray Scanner', ARRAY['Baggage', 'Parcel'], ARRAY['Tables', 'Bins'], 'Tunnel size, throughput', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['x-ray', 'baggage', 'scanner'], 500, 1500),
('SEC-013', 'Safety & Security', 'Security Equipment', 'CCTV/Surveillance Camera', ARRAY['Fixed', 'PTZ', 'Wireless'], ARRAY['DVR', 'Monitors', 'Cables'], 'Resolution, features', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['CCTV', 'camera', 'surveillance'], 50, 200),
('SEC-014', 'Safety & Security', 'Security Equipment', 'Access Control System', ARRAY['RFID', 'Barcode', 'Biometric'], ARRAY['Readers', 'Turnstiles'], 'Capacity, features', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['access control', 'RFID', 'credentials'], 200, 1000),
('SEC-015', 'Safety & Security', 'Security Equipment', 'Two-Way Radios', ARRAY['Analog', 'Digital', 'Trunked'], ARRAY['Chargers', 'Earpieces'], 'Channels, range', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['radio', 'walkie talkie', 'two-way'], 10, 40),
('SEC-016', 'Safety & Security', 'Security Equipment', 'Crowd Barrier/Barricade', ARRAY['Steel Barrier', 'Bike Rack', 'Water Filled'], ARRAY['Connectors', 'Signs'], 'Length, height', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['barrier', 'barricade', 'crowd control'], 10, 40)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SAFETY & SECURITY - MEDICAL
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('MED-001', 'Safety & Security', 'Medical Services', 'EMT/Paramedic', ARRAY['EMT-Basic', 'Paramedic', 'Nurse'], ARRAY['Medical Kit', 'Radio'], 'Certification level', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'sports', 'construction']::industry_vertical[], ARRAY['EMT', 'paramedic', 'medical'], 35, 100),
('MED-002', 'Safety & Security', 'Medical Services', 'Ambulance', ARRAY['BLS', 'ALS', 'Standby'], ARRAY['Crew', 'Equipment'], 'Level of care', 'Per Unit/Hour', 'service', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['ambulance', 'emergency'], 150, 500),
('MED-003', 'Safety & Security', 'Medical Services', 'First Aid Kit', ARRAY['Basic', 'Advanced', 'Trauma'], ARRAY['Supplies', 'AED'], 'Contents, capacity', 'Per Kit', 'consumable', ARRAY['universal']::industry_vertical[], ARRAY['first aid', 'kit', 'supplies'], 25, 500),
('MED-004', 'Safety & Security', 'Medical Services', 'AED (Defibrillator)', ARRAY['Automatic', 'Semi-Auto'], ARRAY['Pads', 'Case'], 'Features, pads', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'sports']::industry_vertical[], ARRAY['AED', 'defibrillator'], 50, 150),
('MED-005', 'Safety & Security', 'Medical Services', 'Medical Tent/Station', ARRAY['First Aid Tent', 'Medical Trailer'], ARRAY['Cots', 'Supplies', 'HVAC'], 'Size, equipment', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['medical tent', 'first aid station'], 300, 1500)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- SIGNAGE & BRANDING
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('SGN-001', 'Signage & Branding', 'Banners & Displays', 'Vinyl Banner', ARRAY['Indoor', 'Outdoor', 'Mesh'], ARRAY['Grommets', 'Pole Pockets'], 'Size, finish', 'Per SqFt', 'purchase', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['banner', 'vinyl', 'signage'], 3, 15),
('SGN-002', 'Signage & Branding', 'Banners & Displays', 'Retractable Banner Stand', ARRAY['Standard', 'Premium', 'Double-Sided'], ARRAY['Carrying Case', 'Lights'], 'Size, quality', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['retractable', 'banner stand', 'roll-up'], 25, 100),
('SGN-003', 'Signage & Branding', 'Banners & Displays', 'Pop-Up Display', ARRAY['Curved', 'Straight', 'Fabric'], ARRAY['Lights', 'Counter', 'Case'], 'Size, configuration', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['pop-up', 'display', 'backdrop'], 75, 300),
('SGN-004', 'Signage & Branding', 'Banners & Displays', 'Fabric Tension Display', ARRAY['SEG Frame', 'Silicone Edge'], ARRAY['Lights', 'Cases'], 'Size, frame type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['fabric', 'tension', 'SEG'], 100, 500),
('SGN-005', 'Signage & Branding', 'Banners & Displays', 'Flag/Feather Banner', ARRAY['Teardrop', 'Feather', 'Rectangle'], ARRAY['Base', 'Stake', 'Case'], 'Size, shape', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'retail', 'sports']::industry_vertical[], ARRAY['flag', 'feather', 'banner'], 50, 200),
('SGN-006', 'Signage & Branding', 'Wayfinding', 'Directional Signage', ARRAY['Post & Panel', 'A-Frame', 'Floor Standing'], ARRAY['Stakes', 'Weights'], 'Size, material', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['directional', 'wayfinding', 'arrows'], 25, 150),
('SGN-007', 'Signage & Branding', 'Wayfinding', 'A-Frame/Sandwich Board', ARRAY['Plastic', 'Metal', 'Chalkboard'], ARRAY['Inserts', 'Weights'], 'Size, material', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'retail', 'hospitality']::industry_vertical[], ARRAY['A-frame', 'sandwich board'], 15, 75),
('SGN-008', 'Signage & Branding', 'Digital Signage', 'Digital Display/Kiosk', ARRAY['Touch Screen', 'Non-Touch', 'Outdoor'], ARRAY['Content', 'Mount'], 'Size, resolution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['digital', 'kiosk', 'display'], 150, 600)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- FURNITURE & DÉCOR - SEATING
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('FRN-001', 'Furniture & Décor', 'Seating', 'Folding Chair', ARRAY['Plastic', 'Padded', 'Chiavari'], ARRAY['Covers', 'Ties'], 'Style, material', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['chair', 'folding', 'seating'], 2, 15),
('FRN-002', 'Furniture & Décor', 'Seating', 'Banquet Chair', ARRAY['Stacking', 'Upholstered'], ARRAY['Covers', 'Ties'], 'Style, fabric', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['banquet chair', 'stacking'], 3, 12),
('FRN-003', 'Furniture & Décor', 'Seating', 'Lounge Furniture', ARRAY['Sofa', 'Loveseat', 'Chair', 'Ottoman'], ARRAY['Pillows', 'Throws'], 'Style, color', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['lounge', 'sofa', 'furniture'], 75, 400),
('FRN-004', 'Furniture & Décor', 'Seating', 'Bar Stool', ARRAY['Backless', 'With Back', 'Adjustable'], ARRAY['Foot Rail'], 'Height, style', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['bar stool', 'high chair'], 10, 50),
('FRN-005', 'Furniture & Décor', 'Seating', 'Bench', ARRAY['Wooden', 'Upholstered', 'Outdoor'], ARRAY['Cushions'], 'Length, style', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['bench', 'seating'], 25, 150)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- FURNITURE & DÉCOR - TABLES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('FRN-010', 'Furniture & Décor', 'Tables', 'Banquet Table', ARRAY['6ft', '8ft', 'Round 60"', 'Round 72"'], ARRAY['Linens', 'Skirting'], 'Size, shape', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['banquet table', 'folding table'], 8, 25),
('FRN-011', 'Furniture & Décor', 'Tables', 'Cocktail/Highboy Table', ARRAY['30" Round', '36" Round', 'Square'], ARRAY['Linens', 'Spandex'], 'Size, height', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['cocktail table', 'highboy', 'standing'], 12, 40),
('FRN-012', 'Furniture & Décor', 'Tables', 'Coffee Table', ARRAY['Wood', 'Glass', 'Acrylic'], ARRAY['Décor'], 'Size, style', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['coffee table', 'lounge'], 25, 150),
('FRN-013', 'Furniture & Décor', 'Tables', 'Registration/Check-In Table', ARRAY['6ft', '8ft', 'Curved'], ARRAY['Linens', 'Skirting'], 'Size, configuration', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['registration', 'check-in', 'table'], 15, 50),
('FRN-014', 'Furniture & Décor', 'Tables', 'Conference Table', ARRAY['Modular', 'Boardroom', 'U-Shape'], ARRAY['Power', 'AV'], 'Size, configuration', 'Per Unit/Day', 'rental', ARRAY['corporate_meetings']::industry_vertical[], ARRAY['conference table', 'meeting'], 50, 300)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;
