-- 0110_universal_catalog_items_part5.sql
-- Universal Catalog - Climate, Waste, Permits, Professional Services, Marketing, Tech Services, Staffing

-- CLIMATE CONTROL
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('CLM-001', 'Climate Control', 'HVAC Systems', 'Portable AC Unit', ARRAY['1 Ton', '2 Ton', '5 Ton', '10 Ton'], ARRAY['Ducting', 'Power'], 'BTU, coverage area', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['AC', 'air conditioning', 'cooling'], 150, 800),
('CLM-002', 'Climate Control', 'HVAC Systems', 'Tent AC System', ARRAY['Package Unit', 'Split System'], ARRAY['Ducting', 'Diffusers'], 'Tonnage, tent size', 'Per Ton/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['tent AC', 'HVAC'], 100, 300),
('CLM-003', 'Climate Control', 'HVAC Systems', 'Industrial Heater', ARRAY['Propane', 'Electric', 'Indirect'], ARRAY['Fuel', 'Ducting'], 'BTU, fuel type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['heater', 'heating', 'propane'], 100, 500),
('CLM-004', 'Climate Control', 'Portable Climate', 'Industrial Fan', ARRAY['Drum Fan', 'Blower', 'Misting Fan'], ARRAY['Extension Cords'], 'CFM, size', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['fan', 'blower', 'ventilation'], 25, 100),
('CLM-005', 'Climate Control', 'Portable Climate', 'Evaporative Cooler', ARRAY['Portable', 'Industrial'], ARRAY['Water Supply', 'Ducting'], 'CFM, coverage', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['swamp cooler', 'evaporative'], 75, 300),
('CLM-006', 'Climate Control', 'Portable Climate', 'Patio Heater', ARRAY['Propane', 'Electric', 'Natural Gas'], ARRAY['Fuel', 'Covers'], 'BTU, fuel type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['patio heater', 'outdoor'], 35, 100),
('CLM-007', 'Climate Control', 'Portable Climate', 'Misting System', ARRAY['Portable', 'Tent Line', 'Fan Mounted'], ARRAY['Water Supply', 'Pump'], 'Coverage, pressure', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'sports']::industry_vertical[], ARRAY['misting', 'cooling', 'outdoor'], 50, 250)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- WASTE MANAGEMENT
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('WST-001', 'Waste Management', 'Waste Collection', 'Trash Receptacle', ARRAY['32 Gal', '55 Gal', 'Decorative'], ARRAY['Liners', 'Lids'], 'Size, style', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['trash can', 'garbage', 'waste'], 10, 40),
('WST-002', 'Waste Management', 'Waste Collection', 'Recycling Station', ARRAY['Single Stream', 'Multi-Stream'], ARRAY['Liners', 'Signage'], 'Streams, capacity', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['recycling', 'bins', 'sustainability'], 25, 100),
('WST-003', 'Waste Management', 'Waste Collection', 'Dumpster', ARRAY['2 Yard', '4 Yard', '6 Yard', '8 Yard'], ARRAY['Pickup Service'], 'Size, pickup frequency', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['dumpster', 'waste container'], 50, 200),
('WST-004', 'Waste Management', 'Waste Collection', 'Roll-Off Container', ARRAY['10 Yard', '20 Yard', '30 Yard', '40 Yard'], ARRAY['Pickup Service'], 'Size, debris type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['roll-off', 'container', 'debris'], 150, 500),
('WST-005', 'Waste Management', 'Waste Collection', 'Compactor', ARRAY['Self-Contained', 'Stationary'], ARRAY['Service', 'Power'], 'Capacity, compaction', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'retail']::industry_vertical[], ARRAY['compactor', 'trash'], 200, 600),
('WST-006', 'Waste Management', 'Cleaning Services', 'Janitorial Service', ARRAY['Day Porter', 'Night Cleaning', 'Event Cleaning'], ARRAY['Supplies', 'Equipment'], 'Scope, frequency', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'hospitality']::industry_vertical[], ARRAY['janitorial', 'cleaning', 'janitor'], 20, 40),
('WST-007', 'Waste Management', 'Cleaning Services', 'Pressure Washing', ARRAY['Hot Water', 'Cold Water'], ARRAY['Equipment', 'Chemicals'], 'Area, surface type', 'Per SqFt', 'service', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['pressure washing', 'cleaning'], 0.10, 0.50),
('WST-008', 'Waste Management', 'Cleaning Services', 'Post-Event Cleanup', ARRAY['Basic', 'Deep Clean', 'Restoration'], ARRAY['Crew', 'Equipment'], 'Scope, timeline', 'Per Event', 'service', ARRAY['events_entertainment']::industry_vertical[], ARRAY['cleanup', 'post-event', 'restoration'], 500, 5000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- PERMITS & COMPLIANCE
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('PRM-001', 'Permits & Compliance', 'Licenses & Permits', 'Event Permit', ARRAY['Special Event', 'Street Closure', 'Park Use'], ARRAY['Application', 'Insurance'], 'Jurisdiction, type', 'Per Permit', 'license', ARRAY['events_entertainment']::industry_vertical[], ARRAY['permit', 'event permit', 'license'], 100, 5000),
('PRM-002', 'Permits & Compliance', 'Licenses & Permits', 'Liquor License/Permit', ARRAY['Temporary', 'Special Event', 'Catering'], ARRAY['Application', 'Insurance'], 'Jurisdiction, duration', 'Per Permit', 'license', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['liquor', 'alcohol', 'permit'], 50, 1000),
('PRM-003', 'Permits & Compliance', 'Licenses & Permits', 'Fire Marshal Permit', ARRAY['Assembly', 'Tent', 'Pyro'], ARRAY['Inspection', 'Plans'], 'Occupancy, features', 'Per Permit', 'license', ARRAY['events_entertainment']::industry_vertical[], ARRAY['fire', 'marshal', 'permit'], 100, 2000),
('PRM-004', 'Permits & Compliance', 'Licenses & Permits', 'Health Department Permit', ARRAY['Food Service', 'Temporary Food'], ARRAY['Inspection', 'Plans'], 'Food handling, scope', 'Per Permit', 'license', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['health', 'food', 'permit'], 50, 500),
('PRM-005', 'Permits & Compliance', 'Licenses & Permits', 'Noise Permit/Variance', ARRAY['Extended Hours', 'Amplified Sound'], ARRAY['Application', 'Monitoring'], 'Hours, decibel limits', 'Per Permit', 'license', ARRAY['events_entertainment']::industry_vertical[], ARRAY['noise', 'sound', 'permit'], 50, 500),
('PRM-006', 'Permits & Compliance', 'Insurance', 'Event Liability Insurance', ARRAY['General Liability', 'Liquor Liability'], ARRAY['Certificate'], 'Coverage, limits', 'Per Event', 'service', ARRAY['events_entertainment']::industry_vertical[], ARRAY['insurance', 'liability', 'coverage'], 200, 5000),
('PRM-007', 'Permits & Compliance', 'Insurance', 'Equipment Insurance', ARRAY['Rental Coverage', 'Owned Equipment'], ARRAY['Certificate', 'Inventory'], 'Value, deductible', 'Per Event', 'service', ARRAY['events_entertainment']::industry_vertical[], ARRAY['equipment', 'insurance', 'rental'], 100, 2000),
('PRM-008', 'Permits & Compliance', 'Insurance', 'Cancellation Insurance', ARRAY['Weather', 'Full Coverage'], ARRAY['Policy'], 'Coverage triggers', 'Per Event', 'service', ARRAY['events_entertainment']::industry_vertical[], ARRAY['cancellation', 'insurance', 'weather'], 500, 10000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- PROFESSIONAL SERVICES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('PRO-001', 'Professional Services', 'Legal Services', 'Contract Review', ARRAY['Vendor', 'Venue', 'Talent'], ARRAY['Documents'], 'Complexity, urgency', 'Per Contract', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['legal', 'contract', 'review'], 200, 2000),
('PRO-002', 'Professional Services', 'Legal Services', 'Licensing/Rights', ARRAY['Music', 'Content', 'Trademark'], ARRAY['Agreements'], 'Scope, duration', 'Per License', 'license', ARRAY['events_entertainment']::industry_vertical[], ARRAY['licensing', 'rights', 'music'], 100, 10000),
('PRO-003', 'Professional Services', 'Accounting', 'Event Accounting', ARRAY['Budgeting', 'Reconciliation', 'Reporting'], ARRAY['Software'], 'Scope, complexity', 'Per Event', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['accounting', 'budget', 'finance'], 500, 5000),
('PRO-004', 'Professional Services', 'Consulting', 'Event Consultant', ARRAY['Strategy', 'Operations', 'Safety'], ARRAY['Reports'], 'Expertise, duration', 'Per Day', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['consultant', 'advisor', 'expert'], 500, 2500),
('PRO-005', 'Professional Services', 'Consulting', 'Accessibility Consultant', ARRAY['ADA Compliance', 'Inclusive Design'], ARRAY['Reports', 'Plans'], 'Scope, certification', 'Per Project', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['accessibility', 'ADA', 'inclusive'], 500, 3000),
('PRO-006', 'Professional Services', 'Consulting', 'Sustainability Consultant', ARRAY['Green Event', 'Carbon Offset', 'Waste Diversion'], ARRAY['Reports', 'Certification'], 'Scope, goals', 'Per Project', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['sustainability', 'green', 'eco'], 500, 5000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- MARKETING & PROMOTION
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('MKT-001', 'Marketing & Promotion', 'Print Materials', 'Event Program', ARRAY['Booklet', 'Folded', 'Single Sheet'], ARRAY['Design'], 'Pages, quantity', 'Per Unit', 'purchase', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['program', 'booklet', 'print'], 1, 15),
('MKT-002', 'Marketing & Promotion', 'Print Materials', 'Poster/Flyer', ARRAY['11x17', '18x24', '24x36'], ARRAY['Design', 'Distribution'], 'Size, quantity', 'Per Unit', 'purchase', ARRAY['events_entertainment', 'retail']::industry_vertical[], ARRAY['poster', 'flyer', 'print'], 0.50, 10),
('MKT-003', 'Marketing & Promotion', 'Print Materials', 'Name Badges', ARRAY['Printed', 'Blank', 'Lanyard'], ARRAY['Holders', 'Lanyards'], 'Style, quantity', 'Per Unit', 'purchase', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['badge', 'name tag', 'credential'], 0.50, 5),
('MKT-004', 'Marketing & Promotion', 'Digital Marketing', 'Social Media Management', ARRAY['Pre-Event', 'Live Coverage', 'Post-Event'], ARRAY['Content', 'Graphics'], 'Platforms, duration', 'Per Day', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['social media', 'marketing', 'digital'], 200, 1000),
('MKT-005', 'Marketing & Promotion', 'Digital Marketing', 'Email Marketing', ARRAY['Invitations', 'Reminders', 'Follow-up'], ARRAY['Design', 'List'], 'Sends, audience', 'Per Campaign', 'service', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['email', 'marketing', 'campaign'], 100, 1000),
('MKT-006', 'Marketing & Promotion', 'Merchandise', 'Branded Apparel', ARRAY['T-Shirt', 'Hat', 'Jacket'], ARRAY['Design', 'Sizing'], 'Item, quantity', 'Per Unit', 'purchase', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['apparel', 't-shirt', 'merchandise'], 5, 100),
('MKT-007', 'Marketing & Promotion', 'Merchandise', 'Promotional Items', ARRAY['Pens', 'Bags', 'Drinkware', 'Tech'], ARRAY['Branding', 'Packaging'], 'Item, quantity', 'Per Unit', 'purchase', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['promotional', 'swag', 'giveaway'], 1, 50)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- TECHNOLOGY SERVICES
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('TCH-001', 'Technology Services', 'Registration Systems', 'Registration Platform', ARRAY['Online', 'On-Site', 'Hybrid'], ARRAY['Hardware', 'Support'], 'Attendees, features', 'Per Event', 'subscription', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['registration', 'ticketing', 'platform'], 500, 10000),
('TCH-002', 'Technology Services', 'Registration Systems', 'Badge Printing System', ARRAY['On-Demand', 'Pre-Printed', 'Self-Service'], ARRAY['Printers', 'Supplies'], 'Volume, features', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['badge', 'printing', 'credentials'], 200, 1000),
('TCH-003', 'Technology Services', 'Registration Systems', 'Check-In Kiosk', ARRAY['Self-Service', 'Staffed', 'Mobile'], ARRAY['Tablets', 'Stands'], 'Stations, features', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['check-in', 'kiosk', 'self-service'], 100, 400),
('TCH-004', 'Technology Services', 'Event Apps', 'Event Mobile App', ARRAY['Native', 'Web App', 'White Label'], ARRAY['Content', 'Support'], 'Features, users', 'Per Event', 'subscription', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['app', 'mobile', 'event app'], 1000, 25000),
('TCH-005', 'Technology Services', 'Event Apps', 'Audience Response System', ARRAY['Polling', 'Q&A', 'Gamification'], ARRAY['Devices', 'Support'], 'Participants, features', 'Per Event', 'subscription', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['polling', 'audience response', 'engagement'], 200, 2000),
('TCH-006', 'Technology Services', 'Analytics', 'Event Analytics Platform', ARRAY['Attendance', 'Engagement', 'ROI'], ARRAY['Integration', 'Reports'], 'Metrics, reporting', 'Per Event', 'subscription', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['analytics', 'data', 'reporting'], 500, 5000),
('TCH-007', 'Technology Services', 'Analytics', 'Lead Retrieval System', ARRAY['Badge Scan', 'App-Based', 'Integrated'], ARRAY['Devices', 'Export'], 'Leads, features', 'Per Event', 'subscription', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['lead retrieval', 'scanning', 'leads'], 200, 2000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;

-- STAFFING
INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('STF-001', 'Staffing', 'General Labor', 'Setup/Strike Crew', ARRAY['General Labor', 'Skilled Labor'], ARRAY['Tools', 'PPE'], 'Experience, tasks', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['setup', 'strike', 'labor'], 18, 35),
('STF-002', 'Staffing', 'General Labor', 'Runner/PA', ARRAY['Runner', 'Production Assistant'], ARRAY['Radio', 'Vehicle'], 'Experience, vehicle', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['runner', 'PA', 'assistant'], 150, 300),
('STF-003', 'Staffing', 'General Labor', 'Warehouse Staff', ARRAY['Picker', 'Packer', 'Loader'], ARRAY['Equipment', 'PPE'], 'Experience, tasks', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'logistics']::industry_vertical[], ARRAY['warehouse', 'logistics', 'labor'], 18, 30),
('STF-004', 'Staffing', 'Specialized Staff', 'Interpreter', ARRAY['ASL', 'Spanish', 'Mandarin', 'Other'], ARRAY['Equipment'], 'Language, certification', 'Per Person/Hour', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'government']::industry_vertical[], ARRAY['interpreter', 'translation', 'ASL'], 50, 150),
('STF-005', 'Staffing', 'Specialized Staff', 'Photographer', ARRAY['Event', 'Portrait', 'Product'], ARRAY['Equipment', 'Editing'], 'Style, deliverables', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['photographer', 'photo', 'photography'], 500, 2500),
('STF-006', 'Staffing', 'Specialized Staff', 'Videographer', ARRAY['Event', 'Documentary', 'Promotional'], ARRAY['Equipment', 'Editing'], 'Style, deliverables', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['videographer', 'video', 'filming'], 600, 3000),
('STF-007', 'Staffing', 'Specialized Staff', 'Hair & Makeup Artist', ARRAY['Makeup', 'Hair', 'Both'], ARRAY['Kit', 'Supplies'], 'Style, subjects', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['makeup', 'hair', 'stylist'], 400, 1500),
('STF-008', 'Staffing', 'Specialized Staff', 'Wardrobe/Stylist', ARRAY['Wardrobe', 'Stylist', 'Dresser'], ARRAY['Supplies', 'Steamer'], 'Scope, subjects', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['wardrobe', 'stylist', 'costume'], 400, 1500),
('STF-009', 'Staffing', 'Volunteer Coordination', 'Volunteer Coordinator', ARRAY['Coordinator', 'Manager'], ARRAY['Radio', 'Materials'], 'Experience, scope', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'nonprofit']::industry_vertical[], ARRAY['volunteer', 'coordinator'], 200, 500),
('STF-010', 'Staffing', 'Volunteer Coordination', 'Volunteer Training', ARRAY['Orientation', 'Role-Specific'], ARRAY['Materials', 'Venue'], 'Duration, attendees', 'Per Session', 'service', ARRAY['events_entertainment', 'nonprofit']::industry_vertical[], ARRAY['training', 'volunteer', 'orientation'], 200, 1000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, specifications = EXCLUDED.specifications, industry_verticals = EXCLUDED.industry_verticals;
