-- 0107_universal_catalog_items_part2.sql
-- Universal Multi-Industry Advancing Catalog - Video, Staging, Rigging, Power

-- ============================================================================
-- TECHNICAL - VIDEO (TECH-VID) - 20 Items
-- ============================================================================

INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('VID-001', 'Technical', 'Video', 'LED Video Wall', ARRAY['Indoor Fine Pitch', 'Outdoor', 'Flexible'], ARRAY['Processors', 'Rigging'], 'Pixel pitch, brightness', 'Per SqM/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'retail']::industry_vertical[], ARRAY['LED wall', 'video wall', 'screen'], 200, 1000),
('VID-002', 'Technical', 'Video', 'Projection Screen', ARRAY['Front', 'Rear', 'Fastfold', 'Truss'], ARRAY['Frames', 'Legs', 'Drape'], 'Size, gain, aspect ratio', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['screen', 'projection', 'fastfold'], 100, 800),
('VID-003', 'Technical', 'Video', 'Projector - Large Venue', ARRAY['20K+', '30K+', 'Laser'], ARRAY['Lenses', 'Rigging'], 'Lumens, resolution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['projector', 'large venue', 'laser'], 500, 3000),
('VID-004', 'Technical', 'Video', 'Projector - Standard', ARRAY['5K-15K', 'Short Throw', 'UST'], ARRAY['Mounts', 'Cables'], 'Lumens, resolution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'education']::industry_vertical[], ARRAY['projector', 'standard'], 150, 600),
('VID-005', 'Technical', 'Video', 'Video Switcher/Mixer', ARRAY['Analog Way', 'Barco', 'Ross', 'Blackmagic'], ARRAY['Cables', 'Multiviewer'], 'Inputs, outputs, layers', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['switcher', 'mixer', 'video'], 300, 2500),
('VID-006', 'Technical', 'Video', 'Media Server', ARRAY['Disguise', 'Watchout', 'Resolume'], ARRAY['Backup Server', 'Cables'], 'Outputs, codec support', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['media server', 'playback'], 400, 2000),
('VID-007', 'Technical', 'Video', 'Camera - Broadcast', ARRAY['Sony', 'Panasonic', 'Blackmagic'], ARRAY['Lenses', 'Tripods'], 'Sensor, resolution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['camera', 'broadcast', 'IMAG'], 300, 1500),
('VID-008', 'Technical', 'Video', 'Camera - PTZ', ARRAY['Sony', 'Panasonic', 'PTZOptics'], ARRAY['Controllers', 'Mounts'], 'Resolution, zoom', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['PTZ', 'robotic', 'camera'], 150, 600),
('VID-009', 'Technical', 'Video', 'Camera - Action/POV', ARRAY['GoPro', 'Insta360', 'DJI'], ARRAY['Mounts', 'Batteries'], 'Resolution, stabilization', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'sports', 'film_television']::industry_vertical[], ARRAY['action cam', 'POV', 'GoPro'], 50, 200),
('VID-010', 'Technical', 'Video', 'Video Recording System', ARRAY['Hyperdeck', 'Ki Pro', 'Atomos'], ARRAY['Media', 'Cables'], 'Format, codec', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['recording', 'capture'], 100, 500),
('VID-011', 'Technical', 'Video', 'Streaming Encoder', ARRAY['Hardware', 'Software', 'Bonded Cellular'], ARRAY['Cables', 'Internet'], 'Resolution, bitrate', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['streaming', 'encoder', 'live'], 200, 1000),
('VID-012', 'Technical', 'Video', 'Video Distribution', ARRAY['SDI DA', 'HDMI Splitter', 'Matrix'], ARRAY['Cables', 'Rack'], 'I/O, distance', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['distribution', 'splitter', 'matrix'], 50, 400),
('VID-013', 'Technical', 'Video', 'Confidence Monitor', ARRAY['LCD', 'Teleprompter', 'Countdown'], ARRAY['Stands', 'Cables'], 'Size, resolution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['monitor', 'confidence', 'teleprompter'], 75, 400),
('VID-014', 'Technical', 'Video', 'Video Cables & Converters', ARRAY['SDI', 'HDMI', 'Fiber', 'Converters'], ARRAY['Adapters', 'Testers'], 'Length, format', 'Per Cable/Day', 'rental', ARRAY['universal']::industry_vertical[], ARRAY['cables', 'SDI', 'HDMI', 'fiber'], 10, 200),
('VID-015', 'Technical', 'Video', 'Video Director', ARRAY['TD', 'Director', 'Vision Mixer'], ARRAY['Headset', 'Script'], 'Live switching', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['director', 'TD', 'switching'], 500, 1500),
('VID-016', 'Technical', 'Video', 'Video Engineer', ARRAY['V1', 'Shader', 'Video Tech'], ARRAY['Tools', 'Scopes'], 'System design, color', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['engineer', 'V1', 'video'], 400, 1000),
('VID-017', 'Technical', 'Video', 'Camera Operator', ARRAY['Camera Op', 'Jib Op', 'Steadicam'], ARRAY['Headset', 'Monitor'], 'Framing, movement', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings', 'film_television']::industry_vertical[], ARRAY['camera', 'operator', 'shooter'], 350, 1000),
('VID-018', 'Technical', 'Video', 'Graphics Operator', ARRAY['Playback Op', 'CG Op', 'Lyric Op'], ARRAY['Software', 'Controller'], 'Graphics, lower thirds', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['graphics', 'CG', 'operator'], 300, 800),
('VID-019', 'Technical', 'Video', 'LED Technician', ARRAY['LED Tech', 'Video Wall Tech'], ARRAY['Tools', 'Spares'], 'Setup, calibration', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['LED', 'technician', 'video wall'], 300, 700),
('VID-020', 'Technical', 'Video', 'Virtual Production System', ARRAY['XR Stage', 'Virtual Set', 'AR'], ARRAY['Tracking', 'Rendering'], 'Tracking, render engine', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'film_television', 'corporate_meetings']::industry_vertical[], ARRAY['virtual', 'XR', 'AR'], 5000, 50000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, common_variations = EXCLUDED.common_variations, specifications = EXCLUDED.specifications, standard_unit = EXCLUDED.standard_unit, procurement_type = EXCLUDED.procurement_type, industry_verticals = EXCLUDED.industry_verticals, search_keywords = EXCLUDED.search_keywords, base_price_low = EXCLUDED.base_price_low, base_price_high = EXCLUDED.base_price_high;

-- ============================================================================
-- TECHNICAL - STAGING (TECH-STG) - 15 Items
-- ============================================================================

INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('STG-001', 'Technical', 'Staging', 'Stage Deck - Standard', ARRAY['4x4', '4x8', '6x8', 'Metric'], ARRAY['Legs', 'Stairs', 'Skirting'], 'Size, height, load capacity', 'Per Deck/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['stage', 'deck', 'platform'], 30, 100),
('STG-002', 'Technical', 'Staging', 'Stage Deck - Heavy Duty', ARRAY['Industrial', 'Outdoor', 'Vehicle Load'], ARRAY['Legs', 'Bracing', 'Ramps'], 'Load capacity 500+ PSF', 'Per Deck/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['heavy duty', 'industrial'], 75, 200),
('STG-003', 'Technical', 'Staging', 'Stage Legs', ARRAY['Fixed', 'Telescopic', 'Screw Jack'], ARRAY['Base Plates', 'Levelers'], 'Height range, load', 'Per Set/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['legs', 'supports'], 10, 50),
('STG-004', 'Technical', 'Staging', 'Stage Stairs', ARRAY['Standard', 'ADA Ramp', 'Rolling'], ARRAY['Handrails', 'Non-slip'], 'Height, width', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['stairs', 'steps', 'ramp'], 50, 200),
('STG-005', 'Technical', 'Staging', 'Stage Skirting', ARRAY['Pleated', 'Flat', 'Velour'], ARRAY['Clips', 'Fasteners'], 'Height, color', 'Per Linear Ft/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['skirting', 'drape'], 3, 15),
('STG-006', 'Technical', 'Staging', 'Drum Riser', ARRAY['Elevated', 'Carpeted', 'Isolated'], ARRAY['Legs', 'Skirt', 'Steps'], 'Size, height', 'Per Unit/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['drum riser', 'platform'], 75, 250),
('STG-007', 'Technical', 'Staging', 'Runway/Catwalk', ARRAY['Extension', 'T-Stage', 'Thrust'], ARRAY['Barriers', 'Lighting'], 'Length, width', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'retail']::industry_vertical[], ARRAY['runway', 'catwalk', 'fashion'], 100, 400),
('STG-008', 'Technical', 'Staging', 'Dance Floor', ARRAY['Sprung', 'Marley', 'Vinyl', 'LED'], ARRAY['Subfloor', 'Tape', 'Edging'], 'Size, surface type', 'Per SqFt/Day', 'rental', ARRAY['events_entertainment', 'hospitality']::industry_vertical[], ARRAY['dance floor', 'marley'], 2, 15),
('STG-009', 'Technical', 'Staging', 'Guard Rails/Handrails', ARRAY['Safety Rail', 'ADA Rail', 'Decorative'], ARRAY['Connectors', 'Posts'], 'Height, load rating', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['rails', 'handrails', 'safety'], 15, 50),
('STG-010', 'Technical', 'Staging', 'Mobile Stage', ARRAY['Trailer Stage', 'Hydraulic', 'Quick Deploy'], ARRAY['Roofing', 'Wings'], 'Size, setup time', 'Per Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['mobile stage', 'trailer'], 2000, 10000),
('STG-011', 'Technical', 'Staging', 'Stage Roofing System', ARRAY['Ground Support', 'Suspended', 'Canopy'], ARRAY['Motors', 'Truss', 'Covers'], 'Coverage, clearance', 'Per System/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['roof', 'canopy', 'cover'], 1500, 8000),
('STG-012', 'Technical', 'Staging', 'Orchestra Pit Cover', ARRAY['Deck System', 'Lift System'], ARRAY['Legs', 'Safety Rails'], 'Size, load capacity', 'Per System/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['orchestra pit', 'cover'], 500, 2000),
('STG-013', 'Technical', 'Staging', 'Revolving Stage', ARRAY['Turntable', 'Ring Revolve'], ARRAY['Motor', 'Controls'], 'Diameter, load, speed', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['revolve', 'turntable', 'rotating'], 1000, 5000),
('STG-014', 'Technical', 'Staging', 'Stage Lift/Elevator', ARRAY['Scissor Lift', 'Hydraulic', 'Screw'], ARRAY['Controls', 'Safety'], 'Capacity, travel', 'Per Unit/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['lift', 'elevator', 'platform'], 800, 4000),
('STG-015', 'Technical', 'Staging', 'Staging Crew', ARRAY['Carpenter', 'Deck Crew', 'Loader'], ARRAY['Tools', 'PPE'], 'Setup, strike, run', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['crew', 'carpenter', 'staging'], 250, 500)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, common_variations = EXCLUDED.common_variations, specifications = EXCLUDED.specifications, standard_unit = EXCLUDED.standard_unit, procurement_type = EXCLUDED.procurement_type, industry_verticals = EXCLUDED.industry_verticals, search_keywords = EXCLUDED.search_keywords, base_price_low = EXCLUDED.base_price_low, base_price_high = EXCLUDED.base_price_high;

-- ============================================================================
-- TECHNICAL - RIGGING (TECH-RIG) - 15 Items
-- ============================================================================

INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('RIG-001', 'Technical', 'Rigging', 'Chain Hoist/Motor', ARRAY['1/4 Ton', '1/2 Ton', '1 Ton', '2 Ton'], ARRAY['Controller', 'Chain', 'Safety'], 'Capacity, speed, lift', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['hoist', 'motor', 'chain'], 75, 300),
('RIG-002', 'Technical', 'Rigging', 'Box Truss', ARRAY['12" Box', '20.5" Box', '30" Box'], ARRAY['Corners', 'Clamps', 'Pins'], 'Length, load rating', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['truss', 'box truss', 'structure'], 25, 100),
('RIG-003', 'Technical', 'Rigging', 'Triangle Truss', ARRAY['12" Triangle', '18" Triangle'], ARRAY['Corners', 'Clamps'], 'Length, load rating', 'Per Section/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['truss', 'triangle'], 20, 75),
('RIG-004', 'Technical', 'Rigging', 'Ground Support Tower', ARRAY['Sleeve Block', 'Crank Up', 'Truss Tower'], ARRAY['Ballast', 'Outriggers'], 'Height, load capacity', 'Per Tower/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['tower', 'ground support'], 200, 800),
('RIG-005', 'Technical', 'Rigging', 'Rigging Hardware', ARRAY['Shackles', 'Slings', 'Turnbuckles'], ARRAY['Inspection Tags'], 'WLL, material grade', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['shackle', 'sling', 'hardware'], 5, 50),
('RIG-006', 'Technical', 'Rigging', 'Beam Clamps', ARRAY['Fixed', 'Swivel', 'Truss Clamp'], ARRAY['Safety Cables'], 'WLL, beam size', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['clamp', 'beam', 'attachment'], 10, 50),
('RIG-007', 'Technical', 'Rigging', 'Span Sets/Roundslings', ARRAY['1 Ton', '2 Ton', '5 Ton'], ARRAY['Shackles', 'Tags'], 'WLL, length', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['span set', 'roundsling', 'sling'], 10, 40),
('RIG-008', 'Technical', 'Rigging', 'Wire Rope/Steel Cable', ARRAY['3/8"', '1/2"', '5/8"'], ARRAY['Thimbles', 'Clips'], 'Diameter, length, WLL', 'Per Length/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['wire rope', 'cable', 'steel'], 15, 100),
('RIG-009', 'Technical', 'Rigging', 'Fall Protection System', ARRAY['Harness', 'Lanyard', 'Anchor'], ARRAY['Carabiners', 'Inspection'], 'Certification, fit', 'Per Person/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['harness', 'fall protection', 'safety'], 25, 100),
('RIG-010', 'Technical', 'Rigging', 'Bridles/Spreader Bars', ARRAY['2-Point', '4-Point', 'Spreader'], ARRAY['Shackles', 'Cables'], 'Length, load distribution', 'Per Unit/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['bridle', 'spreader', 'distribution'], 30, 150),
('RIG-011', 'Technical', 'Rigging', 'Motor Controller', ARRAY['8-Way', '12-Way', '24-Way'], ARRAY['Cables', 'Pickles'], 'Channels, features', 'Per Unit/Day', 'rental', ARRAY['events_entertainment']::industry_vertical[], ARRAY['controller', 'motor control'], 100, 500),
('RIG-012', 'Technical', 'Rigging', 'Head Rigger', ARRAY['Certified Rigger', 'Arena Rigger'], ARRAY['Tools', 'Certs'], 'Certification, experience', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['rigger', 'head rigger'], 500, 1000),
('RIG-013', 'Technical', 'Rigging', 'Rigger/Crew', ARRAY['Rigger', 'Ground Rigger', 'Up Rigger'], ARRAY['Tools', 'PPE'], 'Certification level', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['rigger', 'crew'], 300, 600),
('RIG-014', 'Technical', 'Rigging', 'Rigging Design/Engineering', ARRAY['CAD Design', 'Structural Calc', 'PE Stamp'], ARRAY['Software', 'Drawings'], 'Engineering stamps', 'Per Project', 'service', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['design', 'engineering', 'structural'], 500, 5000),
('RIG-015', 'Technical', 'Rigging', 'Automation System', ARRAY['Winch', 'Track', 'Flying'], ARRAY['Controllers', 'Safety'], 'Capacity, speed, control', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'film_television']::industry_vertical[], ARRAY['automation', 'flying', 'winch'], 1000, 10000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, common_variations = EXCLUDED.common_variations, specifications = EXCLUDED.specifications, standard_unit = EXCLUDED.standard_unit, procurement_type = EXCLUDED.procurement_type, industry_verticals = EXCLUDED.industry_verticals, search_keywords = EXCLUDED.search_keywords, base_price_low = EXCLUDED.base_price_low, base_price_high = EXCLUDED.base_price_high;

-- ============================================================================
-- TECHNICAL - POWER DISTRIBUTION (TECH-PWR) - 15 Items
-- ============================================================================

INSERT INTO production_advancing_catalog (item_id, category, subcategory, item_name, common_variations, related_accessories, specifications, standard_unit, procurement_type, industry_verticals, search_keywords, base_price_low, base_price_high) VALUES
('PWR-001', 'Technical', 'Power Distribution', 'Generator', ARRAY['20kW', '45kW', '100kW', '500kW'], ARRAY['Fuel', 'Cables', 'Monitoring'], 'kW output, fuel type', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction', 'film_television']::industry_vertical[], ARRAY['generator', 'power', 'diesel'], 300, 3000),
('PWR-002', 'Technical', 'Power Distribution', 'Main Distribution Panel', ARRAY['200A', '400A', '800A', '1200A'], ARRAY['Cables', 'Breakers'], 'Amperage, phase', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['distro', 'distribution', 'panel'], 150, 800),
('PWR-003', 'Technical', 'Power Distribution', 'Sub Distribution Box', ARRAY['100A', '200A', 'Spider Box'], ARRAY['Cables', 'Adapters'], 'Outputs, amperage', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['sub distro', 'spider', 'breakout'], 50, 200),
('PWR-004', 'Technical', 'Power Distribution', 'Feeder Cable', ARRAY['Cam-Lok', '4/0', '2/0'], ARRAY['Connectors', 'Adapters'], 'Gauge, length', 'Per Cable/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['feeder', 'cam-lok', 'cable'], 15, 100),
('PWR-005', 'Technical', 'Power Distribution', 'Extension Cables', ARRAY['Edison', 'Stage Pin', 'Powercon'], ARRAY['Adapters', 'Splitters'], 'Length, amperage', 'Per Cable/Day', 'rental', ARRAY['universal']::industry_vertical[], ARRAY['extension', 'power cable'], 5, 30),
('PWR-006', 'Technical', 'Power Distribution', 'UPS System', ARRAY['Rack Mount', 'Tower', 'Online'], ARRAY['Batteries', 'Monitoring'], 'VA rating, runtime', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['UPS', 'backup', 'battery'], 75, 500),
('PWR-007', 'Technical', 'Power Distribution', 'Power Conditioner', ARRAY['Voltage Regulator', 'Isolation', 'Surge'], ARRAY['Cables', 'Monitoring'], 'VA rating, features', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'corporate_meetings']::industry_vertical[], ARRAY['conditioner', 'regulator', 'surge'], 50, 300),
('PWR-008', 'Technical', 'Power Distribution', 'Cable Ramps/Protection', ARRAY['Heavy Duty', 'Light Duty', 'ADA'], ARRAY['Connectors', 'Anchoring'], 'Vehicle load, channels', 'Per Section/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['cable ramp', 'protection', 'crossover'], 15, 75),
('PWR-009', 'Technical', 'Power Distribution', 'Power Monitoring', ARRAY['Meter', 'Logger', 'Remote'], ARRAY['Software', 'Cables'], 'Voltage, current, PF', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['monitoring', 'meter', 'power'], 50, 200),
('PWR-010', 'Technical', 'Power Distribution', 'Transformer', ARRAY['Step Down', 'Step Up', 'Isolation'], ARRAY['Cables', 'Protection'], 'kVA, voltage', 'Per Unit/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['transformer', 'voltage'], 100, 500),
('PWR-011', 'Technical', 'Power Distribution', 'Solar/Battery System', ARRAY['Portable Solar', 'Battery Bank', 'Hybrid'], ARRAY['Panels', 'Inverter'], 'kWh capacity, output', 'Per System/Day', 'rental', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['solar', 'battery', 'green'], 200, 1500),
('PWR-012', 'Technical', 'Power Distribution', 'Electrician - Master', ARRAY['Master Electrician', 'Licensed'], ARRAY['Tools', 'Meters'], 'License, experience', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['electrician', 'master', 'licensed'], 500, 1000),
('PWR-013', 'Technical', 'Power Distribution', 'Electrician - Journeyman', ARRAY['Journeyman', 'Apprentice'], ARRAY['Tools', 'PPE'], 'License level', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['electrician', 'journeyman'], 300, 600),
('PWR-014', 'Technical', 'Power Distribution', 'Generator Operator', ARRAY['Certified Operator', 'Fuel Tech'], ARRAY['Tools', 'Monitoring'], 'Certification', 'Per Person/Day', 'labor', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['generator', 'operator'], 300, 600),
('PWR-015', 'Technical', 'Power Distribution', 'Electrical Engineering', ARRAY['Load Calc', 'Single Line', 'Permit Drawings'], ARRAY['Software', 'Stamps'], 'PE stamp if required', 'Per Project', 'service', ARRAY['events_entertainment', 'construction']::industry_vertical[], ARRAY['engineering', 'electrical', 'design'], 500, 5000)
ON CONFLICT (item_id) DO UPDATE SET item_name = EXCLUDED.item_name, common_variations = EXCLUDED.common_variations, specifications = EXCLUDED.specifications, standard_unit = EXCLUDED.standard_unit, procurement_type = EXCLUDED.procurement_type, industry_verticals = EXCLUDED.industry_verticals, search_keywords = EXCLUDED.search_keywords, base_price_low = EXCLUDED.base_price_low, base_price_high = EXCLUDED.base_price_high;
