export const dynamic = 'force-dynamic';

import { Logger } from '@ghxstship/config';
import { NextRequest, NextResponse } from "next/server";
import type { GeneratedBlueprint } from "../../../generator/types";

export const runtime = "edge";

// =============================================================================
// PDF EXPORT API
// Generates a PDF document from a blueprint
// =============================================================================

function generatePDFContent(blueprint: GeneratedBlueprint, isAuthenticated: boolean): string {
  const watermark = isAuthenticated ? "" : `
    <div style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 120px; color: rgba(0,0,0,0.05); z-index: 1000; pointer-events: none;">
      PREVIEW
    </div>
  `;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${blueprint.concept.name} - Experience Blueprint</title>
  <style>
    @page { size: letter; margin: 0.75in; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { 
      font-family: 'Helvetica Neue', Arial, sans-serif; 
      font-size: 10pt; 
      line-height: 1.4;
      color: #1a1a1a;
    }
    .page { page-break-after: always; }
    .page:last-child { page-break-after: auto; }
    
    h1 { font-size: 28pt; font-weight: 900; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px; }
    h2 { font-size: 16pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin: 24px 0 12px; border-bottom: 3px solid #1a1a1a; padding-bottom: 8px; }
    h3 { font-size: 12pt; font-weight: 700; text-transform: uppercase; margin: 16px 0 8px; }
    
    .header { text-align: center; margin-bottom: 32px; }
    .tagline { font-size: 14pt; font-style: italic; color: #666; margin-bottom: 16px; }
    .meta { font-size: 9pt; color: #999; }
    
    .color-palette { display: flex; gap: 8px; justify-content: center; margin: 16px 0; }
    .color-swatch { width: 40px; height: 40px; border: 2px solid #1a1a1a; }
    
    .grid { display: grid; gap: 16px; }
    .grid-2 { grid-template-columns: 1fr 1fr; }
    .grid-3 { grid-template-columns: 1fr 1fr 1fr; }
    
    .card { border: 2px solid #1a1a1a; padding: 16px; }
    .card-header { font-weight: 700; text-transform: uppercase; margin-bottom: 8px; }
    
    .sense-icon { width: 32px; height: 32px; border: 2px solid #1a1a1a; display: flex; align-items: center; justify-content: center; margin-bottom: 8px; }
    
    .xyz-bar { display: flex; gap: 4px; margin: 8px 0; }
    .xyz-level { width: 24px; height: 24px; border: 2px solid #1a1a1a; }
    .xyz-level.active { background: #1a1a1a; }
    
    .zone-tag { display: inline-block; border: 1px solid #ccc; padding: 4px 8px; margin: 2px; font-size: 9pt; }
    
    .phase { display: flex; gap: 16px; margin: 12px 0; padding: 12px; border-left: 4px solid #1a1a1a; }
    .phase-number { font-size: 24pt; font-weight: 900; color: #ccc; }
    
    .tier { border: 2px solid #1a1a1a; padding: 16px; margin: 8px 0; }
    .tier-budget { font-size: 18pt; font-weight: 900; color: #FF006E; }
    
    .checklist-item { display: flex; gap: 8px; margin: 4px 0; }
    .checkbox { width: 12px; height: 12px; border: 2px solid #1a1a1a; }
    
    .footer { text-align: center; font-size: 8pt; color: #999; margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; }
    
    .cta-box { background: #FF006E; color: white; padding: 24px; text-align: center; margin: 32px 0; }
    .cta-box h3 { color: white; margin-bottom: 8px; }
  </style>
</head>
<body>
  ${watermark}
  
  <!-- PAGE 1: Cover & Concept -->
  <div class="page">
    <div class="header">
      <h1>${blueprint.concept.name}</h1>
      <p class="tagline">"${blueprint.concept.tagline}"</p>
      <div class="color-palette">
        ${blueprint.concept.visualIdentity.colorPalette.map(c => `<div class="color-swatch" style="background: ${c}"></div>`).join("")}
      </div>
      <p class="meta">Generated by ATLVS Experience Generator | ${new Date(blueprint.generatedAt).toLocaleDateString()}</p>
    </div>
    
    <h2>Core Narrative</h2>
    <p>${blueprint.concept.narrative}</p>
    
    <h2>Target Transformation</h2>
    <p>${blueprint.concept.targetTransformation}</p>
    
    <h2>Visual Identity</h2>
    <p><strong>Typography:</strong> ${blueprint.concept.visualIdentity.typography}</p>
    <p><strong>Mood Keywords:</strong> ${blueprint.concept.visualIdentity.moodKeywords.join(", ")}</p>
  </div>
  
  <!-- PAGE 2: Sensory Design -->
  <div class="page">
    <h2>5 Senses Activation Matrix</h2>
    <div class="grid grid-2">
      ${Object.entries(blueprint.sensoryDesign).map(([sense, data]) => `
        <div class="card">
          <div class="card-header">${sense.toUpperCase()}</div>
          <p><strong>Primary:</strong> ${data.primary}</p>
          <p><strong>Secondary:</strong></p>
          <ul>${data.secondary.map(s => `<li>${s}</li>`).join("")}</ul>
          <p><strong>Accessibility:</strong> ${data.accessibility}</p>
        </div>
      `).join("")}
    </div>
  </div>
  
  <!-- PAGE 3: Spatial-Temporal -->
  <div class="page">
    <h2>XYZ Spatial-Temporal Foundation</h2>
    <div class="grid grid-3">
      <div class="card">
        <div class="card-header">X-Axis: Distance</div>
        <div class="xyz-bar">
          ${[1,2,3,4,5].map(l => `<div class="xyz-level ${l <= blueprint.spatialTemporal.x.level ? 'active' : ''}"></div>`).join("")}
        </div>
        <p><strong>${blueprint.spatialTemporal.x.description}</strong></p>
        <p>${blueprint.spatialTemporal.x.rationale}</p>
      </div>
      <div class="card">
        <div class="card-header">Y-Axis: Space</div>
        <div class="xyz-bar">
          ${[1,2,3,4,5].map(l => `<div class="xyz-level ${l <= blueprint.spatialTemporal.y.level ? 'active' : ''}"></div>`).join("")}
        </div>
        <p><strong>${blueprint.spatialTemporal.y.description}</strong></p>
        <p>${blueprint.spatialTemporal.y.rationale}</p>
      </div>
      <div class="card">
        <div class="card-header">Z-Axis: Time</div>
        <div class="xyz-bar">
          ${[1,2,3,4,5].map(l => `<div class="xyz-level ${l <= blueprint.spatialTemporal.z.level ? 'active' : ''}"></div>`).join("")}
        </div>
        <p><strong>${blueprint.spatialTemporal.z.description}</strong></p>
        <p>${blueprint.spatialTemporal.z.rationale}</p>
      </div>
    </div>
    
    <h2>Experience Zones</h2>
    <div>
      ${blueprint.spatialTemporal.zones.map(z => `
        <span class="zone-tag">${z.code}: ${z.name} (Cap: ${z.capacity})</span>
      `).join("")}
    </div>
  </div>
  
  <!-- PAGE 4: Guest Journey -->
  <div class="page">
    <h2>Guest Journey: URL to IRL</h2>
    ${Object.entries(blueprint.guestJourney).map(([_key, phase], i) => `
      <div class="phase">
        <div class="phase-number">${i + 1}</div>
        <div>
          <h3>${phase.name}</h3>
          <p><em>Emotional State: ${phase.emotionalState}</em></p>
          <p><strong>Touchpoints:</strong> ${phase.touchpoints.join(", ")}</p>
          <p><strong>Technology:</strong> ${phase.technology.join(", ")}</p>
        </div>
      </div>
    `).join("")}
  </div>
  
  <!-- PAGE 5: Production Documents -->
  <div class="page">
    <h2>Production Overview</h2>
    <p>${blueprint.documents.onePageOverview}</p>
    
    <h2>Schedule Phases</h2>
    <table style="width: 100%; border-collapse: collapse;">
      <tr style="background: #f5f5f5;">
        <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Phase</th>
        <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Duration</th>
        <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Description</th>
      </tr>
      ${blueprint.documents.schedulePhases.map(p => `
        <tr>
          <td style="padding: 8px; border: 1px solid #ddd;">${p.code}: ${p.name}</td>
          <td style="padding: 8px; border: 1px solid #ddd;">${p.duration}</td>
          <td style="padding: 8px; border: 1px solid #ddd;">${p.description}</td>
        </tr>
      `).join("")}
    </table>
    
    <h2>Credential Types</h2>
    <div class="grid grid-3">
      ${blueprint.documents.credentialTypes.map(c => `
        <div style="display: flex; align-items: center; gap: 8px; margin: 4px 0;">
          <div style="width: 16px; height: 16px; background: ${c.color}; border: 1px solid #000;"></div>
          <span>${c.code}: ${c.name} (L${c.accessLevel})</span>
        </div>
      `).join("")}
    </div>
  </div>
  
  <!-- PAGE 6: Budget Tiers -->
  <div class="page">
    <h2>Scalable Execution Tiers</h2>
    ${Object.entries(blueprint.executionTiers).map(([_key, tier]) => `
      <div class="tier">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <h3>${tier.name}</h3>
          <span class="tier-budget">${tier.budget}</span>
        </div>
        <p>${tier.description}</p>
        <p><strong>Includes:</strong> ${tier.includes.join(", ")}</p>
        ${tier.excludes.length > 0 ? `<p><strong>Excludes:</strong> ${tier.excludes.join(", ")}</p>` : ""}
      </div>
    `).join("")}
    
    <h2>Compliance Checklist</h2>
    ${blueprint.documents.complianceChecklist.map(item => `
      <div class="checklist-item">
        <div class="checkbox"></div>
        <span><strong>${item.category}:</strong> ${item.item} ${item.required ? "(Required)" : "(Optional)"}</span>
      </div>
    `).join("")}
    
    ${!isAuthenticated ? `
      <div class="cta-box">
        <h3>Ready to Launch This Production?</h3>
        <p>Sign up for ATLVS to export this blueprint as a full production project with all templates, org charts, and compliance tracking.</p>
        <p style="margin-top: 16px; font-weight: bold;">atlvs.ghxstship.com/generator</p>
      </div>
    ` : ""}
    
    <div class="footer">
      <p>Generated by ATLVS Experience Generator | Powered by GHXSTSHIP Industries</p>
      <p>This blueprint is for planning purposes. Actual production requirements may vary.</p>
    </div>
  </div>
</body>
</html>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { blueprint, isAuthenticated = false } = body;

    if (!blueprint) {
      return NextResponse.json(
        { error: "Blueprint is required" },
        { status: 400 }
      );
    }

    // Generate HTML content
    const htmlContent = generatePDFContent(blueprint, isAuthenticated);

    // Return HTML that can be printed to PDF by the browser
    return new NextResponse(htmlContent, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `inline; filename="${blueprint.concept.name.replace(/[^a-zA-Z0-9]/g, "_")}_Blueprint.html"`,
      },
    });
  } catch (error) {
    Logger.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}
